#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'U200_dma_ddr4_32G'
#
# Generated by Vivado on Sat Jul 11 19:12:40 BST 2026
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/mr_halfword/fpga_sio/multiple_boards/custom_parts_ddr4_2016_4_and_above.csv"
#    "/home/mr_halfword/fpga_sio/multiple_boards/usr_accesse2_read.vhd"
#    "/home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/AXI_DNA_v1_0_S00_AXI.v"
#    "/home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/DNA_read.vhd"
#    "/home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/AXI_DNA_v1_0.v"
#    "/home/mr_halfword/fpga_sio/U200/constraints/ddr4_c0.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/ddr4_c1.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/ddr4_c2.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/ddr4_c3.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/pcie.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/qspi.xdc"
#    "/home/mr_halfword/fpga_sio/U200/constraints/satellite_controller.xdc"
#    "/home/mr_halfword/fpga_sio/multiple_boards/copy_bitstream_and_debug_probes.tcl"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/../../multiple_boards/custom_parts_ddr4_2016_4_and_above.csv"]"\
 "[file normalize "$origin_dir/../../multiple_boards/usr_accesse2_read.vhd"]"\
 "[file normalize "$origin_dir/../../multiple_boards/ultrascale_dna/AXI_DNA_v1_0_S00_AXI.v"]"\
 "[file normalize "$origin_dir/../../multiple_boards/ultrascale_dna/DNA_read.vhd"]"\
 "[file normalize "$origin_dir/../../multiple_boards/ultrascale_dna/AXI_DNA_v1_0.v"]"\
 "[file normalize "$origin_dir/../../U200/constraints/ddr4_c0.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/ddr4_c1.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/ddr4_c2.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/ddr4_c3.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/pcie.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/qspi.xdc"]"\
 "[file normalize "$origin_dir/../../U200/constraints/satellite_controller.xdc"]"\
 "[file normalize "$origin_dir/../../multiple_boards/copy_bitstream_and_debug_probes.tcl"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "U200_dma_ddr4_32G"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/U200_dma_ddr4_32G"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcu200-fsgd2104-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -id {[BD 41-1306]}  -suppress  -ruleid {19}  -source 2
set_msg_config  -id {[BD 41-1271]}  -suppress  -ruleid {20}  -source 2
set_msg_config  -id {[BD 5-699]}  -suppress  -ruleid {21}  -source 2


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcu200-fsgd2104-2-e" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../multiple_boards/custom_parts_ddr4_2016_4_and_above.csv"] \
 [file normalize "${origin_dir}/../../multiple_boards/usr_accesse2_read.vhd"] \
 [file normalize "${origin_dir}/../../multiple_boards/ultrascale_dna/AXI_DNA_v1_0_S00_AXI.v"] \
 [file normalize "${origin_dir}/../../multiple_boards/ultrascale_dna/DNA_read.vhd"] \
 [file normalize "${origin_dir}/../../multiple_boards/ultrascale_dna/AXI_DNA_v1_0.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../multiple_boards/usr_accesse2_read.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../multiple_boards/ultrascale_dna/DNA_read.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "U200_dma_ddr4_32G_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/ddr4_c0.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/ddr4_c0.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/ddr4_c1.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/ddr4_c1.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/ddr4_c2.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/ddr4_c2.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/ddr4_c3.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/ddr4_c3.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/pcie.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/pcie.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/qspi.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/qspi.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../U200/constraints/satellite_controller.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../U200/constraints/satellite_controller.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcu200-fsgd2104-2-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "AXI_DNA_v1_0" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
set files [list \
 [file normalize "${origin_dir}/../../multiple_boards/copy_bitstream_and_debug_probes.tcl"] \
]
add_files -norecurse -fileset $obj $files

# Set 'utils_1' fileset file properties for remote files
set file "$origin_dir/../../multiple_boards/copy_bitstream_and_debug_probes.tcl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "file_type" -value "TCL" -objects $file_obj


# Set 'utils_1' fileset file properties for local files
# None

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD U200_ddr4_channel
proc cr_bd_U200_ddr4_channel { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name U200_ddr4_channel

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:ddr4:2.2\
  xilinx.com:inline_hdl:ilvector_logic:1.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }


##################################################################
# DATA FILE TCL PROCs
##################################################################

proc write_ddr4_file_U200_ddr4_channel_ddr4_0_0 { str_filepath } {

   file mkdir [ file dirname "$str_filepath" ]
   set data_file [open $str_filepath  w+]

   puts $data_file {Part type,Part name,Rank,StackHeight,CA Mirror,Data mask,Address width,Row width,Column width,Bank width,Bank group width,CS width,CKE width,ODT width,CK width,Memory speed grade,Memory density,Component density,Memory device width,Memory component width,Data bits per strobe,IO Voltages,Data widths,Min period,Max period,tCKE,tFAW,tFAW_dlr,tMRD,tRAS,tRCD,tREFI,tRFC,tRFC_dlr,tRP,tRRD_S,tRRD_L,tRRD_dlr,tRTP,tWR,tWTR_S,tWTR_L,tXPR,tZQCS,tZQINIT,tCCD_3ds,cas latency,cas write latency,burst length}
   puts $data_file {Components,DDR4_CUSTOM,1,1,0,1,17,15,10,2,1,1,1,1,1,107E,4Gb,4Gb,16,16,8,1.2V,"8,16,24,32,40,48,56,64,72,80",1071,1600,5000 ps,30000 ps,0,8 tck,34000 ps,13920 ps,7800000 ps,260000 ps,0,13920 ps,5300 ps,6400 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,270 ns,128 tck,1024 tck,0,13,12,8}
   puts $data_file {UDIMMs,DDR4_CUSTOM1,2,1,1,1,17,15,10,2,2,2,2,2,2,2G1,8GB,1Gb,72,8,8,1.2V,72,1250,1600,5000 ps,30000 ps,0,8 tck,34000 ps,13920 ps,7800000 ps,260000 ps,0,13920 ps,5300 ps,6400 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,270 ns,128 tck,1024 tck,0,12,9,8}
   puts $data_file {SODIMMs,DDR4_CUSTOM2,1,1,0,1,17,15,10,2,2,1,1,1,1,2G1,4GB,512Mb,64,8,8,1.2V,64,1071,1600,5000 ps,30000 ps,0,8 tck,34000 ps,13920 ps,7800000 ps,260000 ps,0,13920 ps,5300 ps,6400 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,270 ns,128 tck,1024 tck,0,14,12,8}
   puts $data_file {RDIMMs,DDR4_CUSTOM3,1,1,0,1,17,15,10,2,2,1,1,1,1,2G1,4GB,512Mb,72,8,8,1.2V,72,938,1600,5000 ps,30000 ps,0,8 tck,34000 ps,13920 ps,7800000 ps,260000 ps,0,13920 ps,5300 ps,6400 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,270 ns,128 tck,1024 tck,0,15,11,8}
   puts $data_file {RDIMMs,DDR4_CUSTOM4,2,2,1,1,17,15,10,2,2,2,2,2,1,83,8GB,4Gb,72,8,8,1.2V,72,833,1600,5000 ps,21000 ps,16 tck,8 tck,32000 ps,14160 ps,7800000 ps,350000 ps,100000 ps,14160 ps,3300 ps,4900 ps,4 tck,7500 ps,15000 ps,2500 ps,7500 ps,360 ns,128 tck,1024 tck,4 tck,16,14,8}
   puts $data_file {RDIMMs,DDR4_CUSTOM5,2,4,1,0,17,16,10,2,2,2,2,2,1,83,16GB,4Gb,72,4,4,1.2V,72,833,1600,5000 ps,13000 ps,16 tck,8 tck,32000 ps,14160 ps,7800000 ps,350000 ps,110000 ps,14160 ps,3300 ps,4900 ps,4 tck,7500 ps,15000 ps,2500 ps,7500 ps,360 ns,128 tck,1024 tck,5 tck,16,14,8}
   puts $data_file {LRDIMMs,DDR4_CUSTOM6,4,1,1,0,17,16,10,2,2,4,2,2,2,093E,32GB,8Gb,72,4,4,1.2V,72,938,1600,5000 ps,15000 ps,0,8 tck,33000 ps,14060 ps,7800000 ps,260000 ps,0,14160 ps,3300 ps,4900 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,360 ns,128 tck,1024 tck,0,15,11,8}
   puts $data_file {RDIMMs,MTA18ASF1G72PZ-2G3,1,1,0,0,17,16,10,2,2,1,1,1,1,83,8GB,4Gb,72,4,4,1.2V,72,833,1600,5000 ps,13328 ps,16 tck,8 tck,33000 ps,14160 ps,7800000 ps,350000 ps,110000 ps,14160 ps,3332 ps,4900 ps,0,7500 ps,15000 ps,2500 ps,7500 ps,360 ns,128 tck,1024 tck,0,17,12,8}

   close $data_file
}
# End of write_ddr4_file_U200_ddr4_channel_ddr4_0_0()



  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 DDR4 ]

  set SYS_CLK [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 SYS_CLK ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300000000} \
   ] $SYS_CLK

  set DDR4_S_AXI_CTRL [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 DDR4_S_AXI_CTRL ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {32} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {32} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {0} \
   CONFIG.HAS_CACHE {0} \
   CONFIG.HAS_LOCK {0} \
   CONFIG.HAS_PROT {0} \
   CONFIG.HAS_QOS {0} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {0} \
   CONFIG.ID_WIDTH {0} \
   CONFIG.NUM_READ_OUTSTANDING {1} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {1} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4LITE} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $DDR4_S_AXI_CTRL

  set DDR4_S_AXI [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 DDR4_S_AXI ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {34} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {4} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $DDR4_S_AXI


  # Create ports
  set init_calib_complete [ create_bd_port -dir O init_calib_complete ]
  set dbg_pllGate [ create_bd_port -dir O dbg_pllGate ]
  set ddr4_ui_clk_sync_rst [ create_bd_port -dir O -type rst ddr4_ui_clk_sync_rst ]
  set PCIE_PERST [ create_bd_port -dir I -type rst PCIE_PERST ]
  set GPIO_DDR4_RESET [ create_bd_port -dir I -type rst GPIO_DDR4_RESET ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $GPIO_DDR4_RESET
  set ddr4_ui_clk [ create_bd_port -dir O -type clk ddr4_ui_clk ]
  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {DDR4_S_AXI_CTRL:DDR4_S_AXI} \
 ] $ddr4_ui_clk
  set_property CONFIG.ASSOCIATED_BUSIF.VALUE_SRC DEFAULT $ddr4_ui_clk


  # Create instance: ddr4_0, and set properties
  set ddr4_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ddr4:2.2 ddr4_0 ]

   # Generate the DDR4 Custom Parts File
   set str_ddr4_folder [get_property IP_DIR [ get_ips [ get_property CONFIG.Component_Name $ddr4_0 ] ] ]
   set str_ddr4_file_name custom_parts_ddr4_2016_4_and_above.csv
   set str_ddr4_file_path ${str_ddr4_folder}/${str_ddr4_file_name}

   write_ddr4_file_U200_ddr4_channel_ddr4_0_0 $str_ddr4_file_path

  set_property -dict [list \
    CONFIG.C0.DDR4_AxiNarrowBurst {true} \
    CONFIG.C0.DDR4_CustomParts {custom_parts_ddr4_2016_4_and_above.csv} \
    CONFIG.C0.DDR4_InputClockPeriod {3332} \
    CONFIG.C0.DDR4_MemoryPart {MTA18ASF1G72PZ-2G3} \
    CONFIG.C0.DDR4_MemoryType {RDIMMs} \
    CONFIG.C0.DDR4_TimePeriod {833} \
    CONFIG.C0.DDR4_isCustom {true} \
    CONFIG.Debug_Signal {Enable} \
  ] $ddr4_0


  # Create instance: ilvector_logic_0, and set properties
  set ilvector_logic_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilvector_logic:1.0 ilvector_logic_0 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {or} \
    CONFIG.C_SIZE {1} \
  ] $ilvector_logic_0


  # Create instance: proc_sys_reset_0, and set properties
  set proc_sys_reset_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_0 ]

  # Create instance: ilvector_logic_1, and set properties
  set ilvector_logic_1 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilvector_logic:1.0 ilvector_logic_1 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $ilvector_logic_1


  # Create interface connections
  connect_bd_intf_net -intf_net DDR4_S_AXI_1 [get_bd_intf_pins ddr4_0/C0_DDR4_S_AXI] [get_bd_intf_ports DDR4_S_AXI]
  connect_bd_intf_net -intf_net DDR4_S_AXI_CTRL_1 [get_bd_intf_pins ddr4_0/C0_DDR4_S_AXI_CTRL] [get_bd_intf_ports DDR4_S_AXI_CTRL]
  connect_bd_intf_net -intf_net SYS_CLK_1 [get_bd_intf_pins ddr4_0/C0_SYS_CLK] [get_bd_intf_ports SYS_CLK]
  connect_bd_intf_net -intf_net ddr4_0_C0_DDR4 [get_bd_intf_pins ddr4_0/C0_DDR4] [get_bd_intf_ports DDR4]

  # Create port connections
  connect_bd_net -net GPIO_DDR4_RESET_1  [get_bd_ports GPIO_DDR4_RESET] \
  [get_bd_pins ilvector_logic_0/Op2]
  connect_bd_net -net PCI_PERSTN_1  [get_bd_ports PCIE_PERST] \
  [get_bd_pins ilvector_logic_1/Op1]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk  [get_bd_pins ddr4_0/c0_ddr4_ui_clk] \
  [get_bd_pins proc_sys_reset_0/slowest_sync_clk] \
  [get_bd_ports ddr4_ui_clk]
  connect_bd_net -net ddr4_0_c0_ddr4_ui_clk_sync_rst  [get_bd_pins ddr4_0/c0_ddr4_ui_clk_sync_rst] \
  [get_bd_ports ddr4_ui_clk_sync_rst] \
  [get_bd_pins proc_sys_reset_0/ext_reset_in]
  connect_bd_net -net ddr4_0_c0_init_calib_complete  [get_bd_pins ddr4_0/c0_init_calib_complete] \
  [get_bd_ports init_calib_complete]
  connect_bd_net -net ddr4_0_dbg_pllGate  [get_bd_pins ddr4_0/dbg_pllGate] \
  [get_bd_ports dbg_pllGate]
  connect_bd_net -net ilvector_logic_0_Res  [get_bd_pins ilvector_logic_0/Res] \
  [get_bd_pins ddr4_0/sys_rst]
  connect_bd_net -net ilvector_logic_1_Res  [get_bd_pins ilvector_logic_1/Res] \
  [get_bd_pins ilvector_logic_0/Op1]
  connect_bd_net -net proc_sys_reset_0_peripheral_aresetn  [get_bd_pins proc_sys_reset_0/peripheral_aresetn] \
  [get_bd_pins ddr4_0/c0_ddr4_aresetn]

  # Create address segments
  assign_bd_address -offset 0x00000000 -range 0x000200000000 -target_address_space [get_bd_addr_spaces DDR4_S_AXI] [get_bd_addr_segs ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces DDR4_S_AXI_CTRL] [get_bd_addr_segs ddr4_0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_U200_ddr4_channel()

cr_bd_U200_ddr4_channel ""
set_property REGISTERED_WITH_MANAGER "1" [get_files U200_ddr4_channel.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files U200_ddr4_channel.bd ] 

if { [get_files [list usr_accesse2_read.vhd]] == "" } {
  import_files -quiet -fileset sources_1 /home/mr_halfword/fpga_sio/multiple_boards/usr_accesse2_read.vhd
}
if { [get_files [list AXI_DNA_v1_0_S00_AXI.v]] == "" } {
  import_files -quiet -fileset sources_1 /home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/AXI_DNA_v1_0_S00_AXI.v
}
if { [get_files [list DNA_read.vhd]] == "" } {
  import_files -quiet -fileset sources_1 /home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/DNA_read.vhd
}
if { [get_files [list AXI_DNA_v1_0.v]] == "" } {
  import_files -quiet -fileset sources_1 /home/mr_halfword/fpga_sio/multiple_boards/ultrascale_dna/AXI_DNA_v1_0.v
}


# Proc to create BD U200_dma_ddr4_32G
proc cr_bd_U200_dma_ddr4_32G { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# usr_accesse2_read, AXI_DNA_v1_0


# The design that will be created by this Tcl proc contains the following 
# block design container source references:
# U200_ddr4_channel



  # CHANGE DESIGN NAME HERE
  set design_name U200_dma_ddr4_32G

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:xdma:4.2\
  xilinx.com:ip:smartconnect:1.0\
  xilinx.com:ip:axi_gpio:2.0\
  xilinx.com:ip:util_ds_buf:2.2\
  xilinx.com:ip:system_management_wiz:1.3\
  xilinx.com:ip:axi_quad_spi:3.2\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:inline_hdl:ilreduced_logic:1.0\
  xilinx.com:inline_hdl:ilconcat:1.0\
  xilinx.com:inline_hdl:ilslice:1.0\
  xilinx.com:inline_hdl:ilconstant:1.0\
  xilinx.com:ip:cms_subsystem:4.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  usr_accesse2_read\
  AXI_DNA_v1_0\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  ##################################################################
  # CHECK Block Design Container Sources
  ##################################################################
  set bCheckSources 1
  set list_bdc_active "U200_ddr4_channel"

  array set map_bdc_missing {}
  set map_bdc_missing(ACTIVE) ""
  set map_bdc_missing(BDC) ""

  if { $bCheckSources == 1 } {
     set list_check_srcs "\ 
  U200_ddr4_channel \
  "

   common::send_gid_msg -ssname BD::TCL -id 2056 -severity "INFO" "Checking if the following sources for block design container exist in the project: $list_check_srcs .\n\n"

   foreach src $list_check_srcs {
      if { [can_resolve_reference $src] == 0 } {
         if { [lsearch $list_bdc_active $src] != -1 } {
            set map_bdc_missing(ACTIVE) "$map_bdc_missing(ACTIVE) $src"
         } else {
            set map_bdc_missing(BDC) "$map_bdc_missing(BDC) $src"
         }
      }
   }

   if { [llength $map_bdc_missing(ACTIVE)] > 0 } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2057 -severity "ERROR" "The following source(s) of Active variants are not found in the project: $map_bdc_missing(ACTIVE)" }
      common::send_gid_msg -ssname BD::TCL -id 2060 -severity "INFO" "Please add source files for the missing source(s) above."
      set bCheckIPsPassed 0
   }
   if { [llength $map_bdc_missing(BDC)] > 0 } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2059 -severity "WARNING" "The following source(s) of variants are not found in the project: $map_bdc_missing(BDC)" }
      common::send_gid_msg -ssname BD::TCL -id 2060 -severity "INFO" "Please add source files for the missing source(s) above."
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set c0_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c0_ddr4 ]

  set SYSCLK0_300 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 SYSCLK0_300 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300000000} \
   ] $SYSCLK0_300

  set c1_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c1_ddr4 ]

  set SYSCLK1_300 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 SYSCLK1_300 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300000000} \
   ] $SYSCLK1_300

  set c2_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c2_ddr4 ]

  set SYSCLK2_300 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 SYSCLK2_300 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300000000} \
   ] $SYSCLK2_300

  set c3_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c3_ddr4 ]

  set SYSCLK3_300 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 SYSCLK3_300 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300000000} \
   ] $SYSCLK3_300

  set PCIE_REFCLK [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 PCIE_REFCLK ]

  set pcie_7x_mgt [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:pcie_7x_mgt_rtl:1.0 pcie_7x_mgt ]


  # Create ports
  set PCIE_PERST [ create_bd_port -dir I -type rst PCIE_PERST ]
  set satellite_uart_txd [ create_bd_port -dir O satellite_uart_txd ]
  set satellite_uart_rxd [ create_bd_port -dir I satellite_uart_rxd ]
  set satellite_gpio [ create_bd_port -dir I -from 3 -to 0 -type intr satellite_gpio ]
  set_property -dict [ list \
   CONFIG.PortWidth {4} \
   CONFIG.SENSITIVITY {EDGE_RISING} \
 ] $satellite_gpio
  set qsfp0_modprs_l [ create_bd_port -dir I -from 0 -to 0 qsfp0_modprs_l ]
  set qsfp1_modprs_l [ create_bd_port -dir I -from 0 -to 0 qsfp1_modprs_l ]
  set qsfp0_int_l [ create_bd_port -dir I -from 0 -to 0 qsfp0_int_l ]
  set qsfp1_int_l [ create_bd_port -dir I -from 0 -to 0 qsfp1_int_l ]
  set qsfp0_lpmode [ create_bd_port -dir O -from 0 -to 0 qsfp0_lpmode ]
  set qsfp1_lpmode [ create_bd_port -dir O -from 0 -to 0 qsfp1_lpmode ]
  set qsfp0_modsel_l [ create_bd_port -dir O -from 0 -to 0 qsfp0_modsel_l ]
  set qsfp1_modsel_l [ create_bd_port -dir O -from 0 -to 0 qsfp1_modsel_l ]
  set qsfp0_reset_l [ create_bd_port -dir O -from 0 -to 0 qsfp0_reset_l ]
  set qsfp1_reset_l [ create_bd_port -dir O -from 0 -to 0 qsfp1_reset_l ]
  set c0_ddr4_alertn [ create_bd_port -dir I c0_ddr4_alertn ]
  set c1_ddr4_alertn [ create_bd_port -dir I c1_ddr4_alertn ]
  set c2_ddr4_alertn [ create_bd_port -dir I c2_ddr4_alertn ]
  set c3_ddr4_alertn [ create_bd_port -dir I c3_ddr4_alertn ]

  # Create instance: xdma_0, and set properties
  set xdma_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xdma:4.2 xdma_0 ]
  set_property -dict [list \
    CONFIG.axil_master_64bit_en {true} \
    CONFIG.axil_master_prefetchable {true} \
    CONFIG.axilite_master_en {true} \
    CONFIG.axilite_master_scale {Kilobytes} \
    CONFIG.axilite_master_size {512} \
    CONFIG.pf0_base_class_menu {Memory_controller} \
    CONFIG.pf0_interrupt_pin {NONE} \
    CONFIG.pf0_msi_enabled {true} \
    CONFIG.pf0_msix_enabled {true} \
    CONFIG.pf0_revision_id {04} \
    CONFIG.pf0_sub_class_interface_menu {RAM} \
    CONFIG.pf0_subsystem_id {002E} \
    CONFIG.pf0_subsystem_vendor_id {0002} \
    CONFIG.pl_link_cap_max_link_speed {8.0_GT/s} \
    CONFIG.pl_link_cap_max_link_width {X16} \
    CONFIG.xdma_pcie_64bit_en {true} \
    CONFIG.xdma_pcie_prefetchable {true} \
  ] $xdma_0


  # Create instance: U200_ddr4_channel_0, and set properties
  set U200_ddr4_channel_0 [ create_bd_cell -type container -reference U200_ddr4_channel U200_ddr4_channel_0 ]
  set_property -dict [list \
    CONFIG.ACTIVE_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.ACTIVE_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.ENABLE_DFX {0} \
    CONFIG.LIST_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.LIST_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.LOCK_PROPAGATE {0} \
  ] $U200_ddr4_channel_0


  set_property SELECTED_SIM_MODEL rtl  $U200_ddr4_channel_0

  # Create instance: U200_ddr4_channel_1, and set properties
  set U200_ddr4_channel_1 [ create_bd_cell -type container -reference U200_ddr4_channel U200_ddr4_channel_1 ]
  set_property -dict [list \
    CONFIG.ACTIVE_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.ACTIVE_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.ENABLE_DFX {0} \
    CONFIG.LIST_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.LIST_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.LOCK_PROPAGATE {0} \
  ] $U200_ddr4_channel_1


  set_property SELECTED_SIM_MODEL rtl  $U200_ddr4_channel_1

  # Create instance: U200_ddr4_channel_2, and set properties
  set U200_ddr4_channel_2 [ create_bd_cell -type container -reference U200_ddr4_channel U200_ddr4_channel_2 ]
  set_property -dict [list \
    CONFIG.ACTIVE_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.ACTIVE_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.ENABLE_DFX {0} \
    CONFIG.LIST_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.LIST_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.LOCK_PROPAGATE {0} \
  ] $U200_ddr4_channel_2


  set_property SELECTED_SIM_MODEL rtl  $U200_ddr4_channel_2

  # Create instance: U200_ddr4_channel_3, and set properties
  set U200_ddr4_channel_3 [ create_bd_cell -type container -reference U200_ddr4_channel U200_ddr4_channel_3 ]
  set_property -dict [list \
    CONFIG.ACTIVE_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.ACTIVE_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.ENABLE_DFX {0} \
    CONFIG.LIST_SIM_BD {U200_ddr4_channel.bd} \
    CONFIG.LIST_SYNTH_BD {U200_ddr4_channel.bd} \
    CONFIG.LOCK_PROPAGATE {0} \
  ] $U200_ddr4_channel_3


  set_property SELECTED_SIM_MODEL rtl  $U200_ddr4_channel_3

  # Create instance: axi_smc, and set properties
  set axi_smc [ create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc ]
  set_property -dict [list \
    CONFIG.NUM_CLKS {6} \
    CONFIG.NUM_MI {10} \
    CONFIG.NUM_SI {1} \
  ] $axi_smc


  # Create instance: axi_smc_1, and set properties
  set axi_smc_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc_1 ]
  set_property -dict [list \
    CONFIG.NUM_CLKS {5} \
    CONFIG.NUM_MI {4} \
    CONFIG.NUM_SI {1} \
  ] $axi_smc_1


  # Create instance: axi_gpio_0, and set properties
  set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0 ]
  set_property CONFIG.C_ALL_INPUTS {1} $axi_gpio_0


  # Create instance: usr_accesse2_read_0, and set properties
  set block_name usr_accesse2_read
  set block_cell_name usr_accesse2_read_0
  if { [catch {set usr_accesse2_read_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $usr_accesse2_read_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: util_ds_buf_0, and set properties
  set util_ds_buf_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 util_ds_buf_0 ]
  set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} $util_ds_buf_0


  # Create instance: system_management_wiz_0, and set properties
  set system_management_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_management_wiz:1.3 system_management_wiz_0 ]
  set_property -dict [list \
    CONFIG.CHANNEL_ENABLE_VP_VN {false} \
    CONFIG.CHANNEL_ENABLE_VUSER0 {true} \
    CONFIG.CHANNEL_ENABLE_VUSER1 {true} \
    CONFIG.CHANNEL_ENABLE_VUSER1_SLAVE0_SSIT {true} \
    CONFIG.CHANNEL_ENABLE_VUSER1_SLAVE1_SSIT {true} \
    CONFIG.CHANNEL_ENABLE_VUSER2 {true} \
    CONFIG.CHANNEL_ENABLE_VUSER2_SLAVE0_SSIT {true} \
    CONFIG.CHANNEL_ENABLE_VUSER2_SLAVE1_SSIT {true} \
    CONFIG.CHANNEL_ENABLE_VUSER3 {true} \
    CONFIG.CHANNEL_ENABLE_VUSER3_SLAVE0_SSIT {true} \
    CONFIG.CHANNEL_ENABLE_VUSER3_SLAVE1_SSIT {true} \
    CONFIG.Enable_Slave0 {true} \
    CONFIG.Enable_Slave1 {true} \
    CONFIG.SELECT_USER_SUPPLY1_SLAVE0_SSIT {VCCINT} \
    CONFIG.SELECT_USER_SUPPLY2_SLAVE0_SSIT {VCCAUX} \
    CONFIG.SELECT_USER_SUPPLY3_SLAVE0_SSIT {VCCO} \
    CONFIG.USER_SUPPLY1_BANK {47} \
    CONFIG.USER_SUPPLY1_SLAVE0_SSIT_BANK {41} \
    CONFIG.USER_SUPPLY1_SLAVE1_SSIT_BANK {71} \
    CONFIG.USER_SUPPLY2_BANK {48} \
    CONFIG.USER_SUPPLY2_SLAVE0_SSIT_BANK {41} \
    CONFIG.USER_SUPPLY2_SLAVE1_SSIT_BANK {71} \
    CONFIG.USER_SUPPLY3_BANK {48} \
    CONFIG.USER_SUPPLY3_SLAVE0_SSIT_BANK {42} \
    CONFIG.USER_SUPPLY3_SLAVE1_SSIT_BANK {72} \
  ] $system_management_wiz_0


  # Create instance: axi_quad_spi_0, and set properties
  set axi_quad_spi_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_quad_spi:3.2 axi_quad_spi_0 ]
  set_property -dict [list \
    CONFIG.C_FIFO_DEPTH {256} \
    CONFIG.C_SPI_MEMORY {2} \
    CONFIG.C_SPI_MODE {2} \
    CONFIG.C_USE_STARTUP {1} \
    CONFIG.C_USE_STARTUP_INT {1} \
  ] $axi_quad_spi_0


  # Create instance: clk_wiz_0, and set properties
  set clk_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0 ]
  set_property -dict [list \
    CONFIG.PRIM_SOURCE {Global_buffer} \
    CONFIG.USE_LOCKED {false} \
    CONFIG.USE_RESET {false} \
  ] $clk_wiz_0


  # Create instance: AXI_DNA_v1_0_0, and set properties
  set block_name AXI_DNA_v1_0
  set block_cell_name AXI_DNA_v1_0_0
  if { [catch {set AXI_DNA_v1_0_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $AXI_DNA_v1_0_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: rst_clk_wiz_0_100M, and set properties
  set rst_clk_wiz_0_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_clk_wiz_0_100M ]

  # Create instance: axi_gpio_1, and set properties
  set axi_gpio_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_1 ]
  set_property -dict [list \
    CONFIG.C_GPIO_WIDTH {9} \
    CONFIG.C_TRI_DEFAULT {0xFFFFFFFE} \
  ] $axi_gpio_1


  # Create instance: ilreduced_logic_0, and set properties
  set ilreduced_logic_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilreduced_logic:1.0 ilreduced_logic_0 ]
  set_property CONFIG.C_SIZE {4} $ilreduced_logic_0


  # Create instance: ilconcat_0, and set properties
  set ilconcat_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconcat:1.0 ilconcat_0 ]
  set_property CONFIG.NUM_PORTS {4} $ilconcat_0


  # Create instance: ilreduced_logic_1, and set properties
  set ilreduced_logic_1 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilreduced_logic:1.0 ilreduced_logic_1 ]
  set_property CONFIG.C_SIZE {4} $ilreduced_logic_1


  # Create instance: ilconcat_1, and set properties
  set ilconcat_1 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconcat:1.0 ilconcat_1 ]
  set_property CONFIG.NUM_PORTS {4} $ilconcat_1


  # Create instance: ilreduced_logic_2, and set properties
  set ilreduced_logic_2 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilreduced_logic:1.0 ilreduced_logic_2 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {or} \
    CONFIG.C_SIZE {4} \
  ] $ilreduced_logic_2


  # Create instance: ilconcat_2, and set properties
  set ilconcat_2 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconcat:1.0 ilconcat_2 ]
  set_property CONFIG.NUM_PORTS {4} $ilconcat_2


  # Create instance: ilslice_0, and set properties
  set ilslice_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilslice:1.0 ilslice_0 ]
  set_property CONFIG.DIN_WIDTH {9} $ilslice_0


  # Create instance: ilconcat_3, and set properties
  set ilconcat_3 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconcat:1.0 ilconcat_3 ]
  set_property CONFIG.NUM_PORTS {9} $ilconcat_3


  # Create instance: clk_wiz_locked, and set properties
  set clk_wiz_locked [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconstant:1.0 clk_wiz_locked ]

  # Create instance: cms_subsystem_0, and set properties
  set cms_subsystem_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:cms_subsystem:4.0 cms_subsystem_0 ]

  # Create interface connections
  connect_bd_intf_net -intf_net PCIE_REFCLK_1 [get_bd_intf_ports PCIE_REFCLK] [get_bd_intf_pins util_ds_buf_0/CLK_IN_D]
  connect_bd_intf_net -intf_net SYS_CLK_1 [get_bd_intf_pins U200_ddr4_channel_0/SYS_CLK] [get_bd_intf_ports SYSCLK0_300]
  connect_bd_intf_net -intf_net SYS_CLK_2 [get_bd_intf_pins U200_ddr4_channel_1/SYS_CLK] [get_bd_intf_ports SYSCLK1_300]
  connect_bd_intf_net -intf_net SYS_CLK_3 [get_bd_intf_pins U200_ddr4_channel_2/SYS_CLK] [get_bd_intf_ports SYSCLK2_300]
  connect_bd_intf_net -intf_net SYS_CLK_4 [get_bd_intf_pins U200_ddr4_channel_3/SYS_CLK] [get_bd_intf_ports SYSCLK3_300]
  connect_bd_intf_net -intf_net U200_ddr4_channel_0_DDR4 [get_bd_intf_pins U200_ddr4_channel_0/DDR4] [get_bd_intf_ports c0_ddr4]
  connect_bd_intf_net -intf_net U200_ddr4_channel_1_DDR4 [get_bd_intf_pins U200_ddr4_channel_1/DDR4] [get_bd_intf_ports c1_ddr4]
  connect_bd_intf_net -intf_net U200_ddr4_channel_2_DDR4 [get_bd_intf_pins U200_ddr4_channel_2/DDR4] [get_bd_intf_ports c2_ddr4]
  connect_bd_intf_net -intf_net U200_ddr4_channel_3_DDR4 [get_bd_intf_pins U200_ddr4_channel_3/DDR4] [get_bd_intf_ports c3_ddr4]
  connect_bd_intf_net -intf_net axi_smc_1_M00_AXI [get_bd_intf_pins axi_smc_1/M00_AXI] [get_bd_intf_pins U200_ddr4_channel_0/DDR4_S_AXI]
  connect_bd_intf_net -intf_net axi_smc_1_M01_AXI [get_bd_intf_pins axi_smc_1/M01_AXI] [get_bd_intf_pins U200_ddr4_channel_1/DDR4_S_AXI]
  connect_bd_intf_net -intf_net axi_smc_1_M02_AXI [get_bd_intf_pins axi_smc_1/M02_AXI] [get_bd_intf_pins U200_ddr4_channel_2/DDR4_S_AXI]
  connect_bd_intf_net -intf_net axi_smc_1_M03_AXI [get_bd_intf_pins axi_smc_1/M03_AXI] [get_bd_intf_pins U200_ddr4_channel_3/DDR4_S_AXI]
  connect_bd_intf_net -intf_net axi_smc_M00_AXI [get_bd_intf_pins axi_smc/M00_AXI] [get_bd_intf_pins U200_ddr4_channel_0/DDR4_S_AXI_CTRL]
  connect_bd_intf_net -intf_net axi_smc_M01_AXI [get_bd_intf_pins axi_smc/M01_AXI] [get_bd_intf_pins U200_ddr4_channel_1/DDR4_S_AXI_CTRL]
  connect_bd_intf_net -intf_net axi_smc_M02_AXI [get_bd_intf_pins axi_smc/M02_AXI] [get_bd_intf_pins U200_ddr4_channel_2/DDR4_S_AXI_CTRL]
  connect_bd_intf_net -intf_net axi_smc_M03_AXI [get_bd_intf_pins axi_smc/M03_AXI] [get_bd_intf_pins U200_ddr4_channel_3/DDR4_S_AXI_CTRL]
  connect_bd_intf_net -intf_net axi_smc_M04_AXI [get_bd_intf_pins axi_smc/M04_AXI] [get_bd_intf_pins axi_gpio_0/S_AXI]
  connect_bd_intf_net -intf_net axi_smc_M05_AXI [get_bd_intf_pins axi_smc/M05_AXI] [get_bd_intf_pins system_management_wiz_0/S_AXI_LITE]
  connect_bd_intf_net -intf_net axi_smc_M06_AXI [get_bd_intf_pins axi_smc/M06_AXI] [get_bd_intf_pins axi_quad_spi_0/AXI_LITE]
  connect_bd_intf_net -intf_net axi_smc_M07_AXI [get_bd_intf_pins axi_smc/M07_AXI] [get_bd_intf_pins AXI_DNA_v1_0_0/s00_axi]
  connect_bd_intf_net -intf_net axi_smc_M08_AXI [get_bd_intf_pins axi_smc/M08_AXI] [get_bd_intf_pins axi_gpio_1/S_AXI]
  connect_bd_intf_net -intf_net axi_smc_M09_AXI [get_bd_intf_pins axi_smc/M09_AXI] [get_bd_intf_pins cms_subsystem_0/s_axi_ctrl]
  connect_bd_intf_net -intf_net xdma_0_M_AXI [get_bd_intf_pins xdma_0/M_AXI] [get_bd_intf_pins axi_smc_1/S00_AXI]
  connect_bd_intf_net -intf_net xdma_0_M_AXI_LITE [get_bd_intf_pins xdma_0/M_AXI_LITE] [get_bd_intf_pins axi_smc/S00_AXI]
  connect_bd_intf_net -intf_net xdma_0_pcie_mgt [get_bd_intf_pins xdma_0/pcie_mgt] [get_bd_intf_ports pcie_7x_mgt]

  # Create port connections
  connect_bd_net -net PCI_PERSTN_1  [get_bd_ports PCIE_PERST] \
  [get_bd_pins xdma_0/sys_rst_n] \
  [get_bd_pins U200_ddr4_channel_0/PCIE_PERST] \
  [get_bd_pins U200_ddr4_channel_1/PCIE_PERST] \
  [get_bd_pins U200_ddr4_channel_2/PCIE_PERST] \
  [get_bd_pins U200_ddr4_channel_3/PCIE_PERST]
  connect_bd_net -net U200_ddr4_channel_0_dbg_pllGate  [get_bd_pins U200_ddr4_channel_0/dbg_pllGate] \
  [get_bd_pins ilconcat_1/In0]
  connect_bd_net -net U200_ddr4_channel_0_ddr4_ui_clk  [get_bd_pins U200_ddr4_channel_0/ddr4_ui_clk] \
  [get_bd_pins axi_smc/aclk] \
  [get_bd_pins axi_smc_1/aclk]
  connect_bd_net -net U200_ddr4_channel_0_ddr4_ui_clk_sync_rst  [get_bd_pins U200_ddr4_channel_0/ddr4_ui_clk_sync_rst] \
  [get_bd_pins ilconcat_2/In0]
  connect_bd_net -net U200_ddr4_channel_0_init_calib_complete  [get_bd_pins U200_ddr4_channel_0/init_calib_complete] \
  [get_bd_pins ilconcat_0/In0]
  connect_bd_net -net U200_ddr4_channel_1_dbg_pllGate  [get_bd_pins U200_ddr4_channel_1/dbg_pllGate] \
  [get_bd_pins ilconcat_1/In1]
  connect_bd_net -net U200_ddr4_channel_1_ddr4_ui_clk  [get_bd_pins U200_ddr4_channel_1/ddr4_ui_clk] \
  [get_bd_pins axi_smc/aclk2] \
  [get_bd_pins axi_smc_1/aclk2]
  connect_bd_net -net U200_ddr4_channel_1_ddr4_ui_clk_sync_rst  [get_bd_pins U200_ddr4_channel_1/ddr4_ui_clk_sync_rst] \
  [get_bd_pins ilconcat_2/In1]
  connect_bd_net -net U200_ddr4_channel_1_init_calib_complete  [get_bd_pins U200_ddr4_channel_1/init_calib_complete] \
  [get_bd_pins ilconcat_0/In1]
  connect_bd_net -net U200_ddr4_channel_2_dbg_pllGate  [get_bd_pins U200_ddr4_channel_2/dbg_pllGate] \
  [get_bd_pins ilconcat_1/In2]
  connect_bd_net -net U200_ddr4_channel_2_ddr4_ui_clk  [get_bd_pins U200_ddr4_channel_2/ddr4_ui_clk] \
  [get_bd_pins axi_smc/aclk3] \
  [get_bd_pins axi_smc_1/aclk3]
  connect_bd_net -net U200_ddr4_channel_2_ddr4_ui_clk_sync_rst  [get_bd_pins U200_ddr4_channel_2/ddr4_ui_clk_sync_rst] \
  [get_bd_pins ilconcat_2/In2]
  connect_bd_net -net U200_ddr4_channel_2_init_calib_complete  [get_bd_pins U200_ddr4_channel_2/init_calib_complete] \
  [get_bd_pins ilconcat_0/In2]
  connect_bd_net -net U200_ddr4_channel_3_dbg_pllGate  [get_bd_pins U200_ddr4_channel_3/dbg_pllGate] \
  [get_bd_pins ilconcat_1/In3]
  connect_bd_net -net U200_ddr4_channel_3_ddr4_ui_clk  [get_bd_pins U200_ddr4_channel_3/ddr4_ui_clk] \
  [get_bd_pins axi_smc/aclk4] \
  [get_bd_pins axi_smc_1/aclk4]
  connect_bd_net -net U200_ddr4_channel_3_ddr4_ui_clk_sync_rst  [get_bd_pins U200_ddr4_channel_3/ddr4_ui_clk_sync_rst] \
  [get_bd_pins ilconcat_2/In3]
  connect_bd_net -net U200_ddr4_channel_3_init_calib_complete  [get_bd_pins U200_ddr4_channel_3/init_calib_complete] \
  [get_bd_pins ilconcat_0/In3]
  connect_bd_net -net axi_gpio_1_gpio_io_o  [get_bd_pins axi_gpio_1/gpio_io_o] \
  [get_bd_pins ilslice_0/Din]
  connect_bd_net -net c0_ddr4_alertn_1  [get_bd_ports c0_ddr4_alertn] \
  [get_bd_pins ilconcat_3/In5]
  connect_bd_net -net c1_ddr4_alertn_1  [get_bd_ports c1_ddr4_alertn] \
  [get_bd_pins ilconcat_3/In6]
  connect_bd_net -net c2_ddr4_alertn_1  [get_bd_ports c2_ddr4_alertn] \
  [get_bd_pins ilconcat_3/In7]
  connect_bd_net -net c3_ddr4_alertn_1  [get_bd_ports c3_ddr4_alertn] \
  [get_bd_pins ilconcat_3/In8]
  connect_bd_net -net clk_wiz_0_clk_out1  [get_bd_pins clk_wiz_0/clk_out1] \
  [get_bd_pins axi_quad_spi_0/ext_spi_clk] \
  [get_bd_pins AXI_DNA_v1_0_0/s00_axi_aclk] \
  [get_bd_pins axi_smc/aclk5] \
  [get_bd_pins rst_clk_wiz_0_100M/slowest_sync_clk]
  connect_bd_net -net clk_wiz_locked_dout  [get_bd_pins clk_wiz_locked/dout] \
  [get_bd_pins ilconcat_3/In1]
  connect_bd_net -net cms_subsystem_0_interrupt_host  [get_bd_pins cms_subsystem_0/interrupt_host] \
  [get_bd_pins xdma_0/usr_irq_req]
  connect_bd_net -net cms_subsystem_0_qsfp0_lpmode  [get_bd_pins cms_subsystem_0/qsfp0_lpmode] \
  [get_bd_ports qsfp0_lpmode]
  connect_bd_net -net cms_subsystem_0_qsfp0_modsel_l  [get_bd_pins cms_subsystem_0/qsfp0_modsel_l] \
  [get_bd_ports qsfp0_modsel_l]
  connect_bd_net -net cms_subsystem_0_qsfp0_reset_l  [get_bd_pins cms_subsystem_0/qsfp0_reset_l] \
  [get_bd_ports qsfp0_reset_l]
  connect_bd_net -net cms_subsystem_0_qsfp1_lpmode  [get_bd_pins cms_subsystem_0/qsfp1_lpmode] \
  [get_bd_ports qsfp1_lpmode]
  connect_bd_net -net cms_subsystem_0_qsfp1_modsel_l  [get_bd_pins cms_subsystem_0/qsfp1_modsel_l] \
  [get_bd_ports qsfp1_modsel_l]
  connect_bd_net -net cms_subsystem_0_qsfp1_reset_l  [get_bd_pins cms_subsystem_0/qsfp1_reset_l] \
  [get_bd_ports qsfp1_reset_l]
  connect_bd_net -net cms_subsystem_0_satellite_uart_txd  [get_bd_pins cms_subsystem_0/satellite_uart_txd] \
  [get_bd_ports satellite_uart_txd]
  connect_bd_net -net ilconcat_0_dout  [get_bd_pins ilconcat_0/dout] \
  [get_bd_pins ilreduced_logic_0/Op1]
  connect_bd_net -net ilconcat_1_dout  [get_bd_pins ilconcat_1/dout] \
  [get_bd_pins ilreduced_logic_1/Op1]
  connect_bd_net -net ilconcat_2_dout  [get_bd_pins ilconcat_2/dout] \
  [get_bd_pins ilreduced_logic_2/Op1]
  connect_bd_net -net ilconcat_3_dout  [get_bd_pins ilconcat_3/dout] \
  [get_bd_pins axi_gpio_1/gpio_io_i]
  connect_bd_net -net ilreduced_logic_0_Res  [get_bd_pins ilreduced_logic_0/Res] \
  [get_bd_pins ilconcat_3/In3]
  connect_bd_net -net ilreduced_logic_1_Res  [get_bd_pins ilreduced_logic_1/Res] \
  [get_bd_pins ilconcat_3/In2]
  connect_bd_net -net ilreduced_logic_2_Res  [get_bd_pins ilreduced_logic_2/Res] \
  [get_bd_pins ilconcat_3/In4]
  connect_bd_net -net ilslice_0_Dout  [get_bd_pins ilslice_0/Dout] \
  [get_bd_pins U200_ddr4_channel_2/GPIO_DDR4_RESET] \
  [get_bd_pins U200_ddr4_channel_3/GPIO_DDR4_RESET] \
  [get_bd_pins U200_ddr4_channel_1/GPIO_DDR4_RESET] \
  [get_bd_pins U200_ddr4_channel_0/GPIO_DDR4_RESET]
  connect_bd_net -net qsfp0_int_l_1  [get_bd_ports qsfp0_int_l] \
  [get_bd_pins cms_subsystem_0/qsfp0_int_l]
  connect_bd_net -net qsfp0_modprs_l_1  [get_bd_ports qsfp0_modprs_l] \
  [get_bd_pins cms_subsystem_0/qsfp0_modprs_l]
  connect_bd_net -net qsfp1_int_l_1  [get_bd_ports qsfp1_int_l] \
  [get_bd_pins cms_subsystem_0/qsfp1_int_l]
  connect_bd_net -net qsfp1_modprs_l_1  [get_bd_ports qsfp1_modprs_l] \
  [get_bd_pins cms_subsystem_0/qsfp1_modprs_l]
  connect_bd_net -net rst_clk_wiz_0_100M_peripheral_aresetn  [get_bd_pins rst_clk_wiz_0_100M/peripheral_aresetn] \
  [get_bd_pins AXI_DNA_v1_0_0/s00_axi_aresetn]
  connect_bd_net -net satellite_gpio_1  [get_bd_ports satellite_gpio] \
  [get_bd_pins cms_subsystem_0/satellite_gpio]
  connect_bd_net -net satellite_uart_rxd_1  [get_bd_ports satellite_uart_rxd] \
  [get_bd_pins cms_subsystem_0/satellite_uart_rxd]
  connect_bd_net -net usr_accesse2_read_0_DATA_OUT  [get_bd_pins usr_accesse2_read_0/DATA_OUT] \
  [get_bd_pins axi_gpio_0/gpio_io_i]
  connect_bd_net -net util_ds_buf_0_IBUF_DS_ODIV2  [get_bd_pins util_ds_buf_0/IBUF_DS_ODIV2] \
  [get_bd_pins xdma_0/sys_clk]
  connect_bd_net -net util_ds_buf_0_IBUF_OUT  [get_bd_pins util_ds_buf_0/IBUF_OUT] \
  [get_bd_pins xdma_0/sys_clk_gt]
  connect_bd_net -net xdma_0_axi_aclk  [get_bd_pins xdma_0/axi_aclk] \
  [get_bd_pins axi_smc/aclk1] \
  [get_bd_pins axi_smc_1/aclk1] \
  [get_bd_pins axi_gpio_0/s_axi_aclk] \
  [get_bd_pins system_management_wiz_0/s_axi_aclk] \
  [get_bd_pins axi_quad_spi_0/s_axi_aclk] \
  [get_bd_pins clk_wiz_0/clk_in1] \
  [get_bd_pins axi_gpio_1/s_axi_aclk] \
  [get_bd_pins cms_subsystem_0/aclk_ctrl]
  connect_bd_net -net xdma_0_axi_aresetn  [get_bd_pins xdma_0/axi_aresetn] \
  [get_bd_pins axi_smc/aresetn] \
  [get_bd_pins axi_smc_1/aresetn] \
  [get_bd_pins axi_gpio_0/s_axi_aresetn] \
  [get_bd_pins system_management_wiz_0/s_axi_aresetn] \
  [get_bd_pins axi_quad_spi_0/s_axi_aresetn] \
  [get_bd_pins rst_clk_wiz_0_100M/ext_reset_in] \
  [get_bd_pins axi_gpio_1/s_axi_aresetn] \
  [get_bd_pins cms_subsystem_0/aresetn_ctrl]

  # Create address segments
  assign_bd_address -offset 0x00000000 -range 0x000200000000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs U200_ddr4_channel_0/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000200000000 -with_name SEG_ddr4_0_C0_DDR4_ADDRESS_BLOCK_1 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs U200_ddr4_channel_1/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000200000000 -with_name SEG_ddr4_0_C0_DDR4_ADDRESS_BLOCK_2 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs U200_ddr4_channel_2/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000600000000 -range 0x000200000000 -with_name SEG_ddr4_0_C0_DDR4_ADDRESS_BLOCK_3 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs U200_ddr4_channel_3/ddr4_0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00008000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs AXI_DNA_v1_0_0/s00_axi/reg0] -force
  assign_bd_address -offset 0x00007000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs axi_gpio_0/S_AXI/Reg] -force
  assign_bd_address -offset 0x00009000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs axi_gpio_1/S_AXI/Reg] -force
  assign_bd_address -offset 0x00006000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs axi_quad_spi_0/AXI_LITE/Reg] -force
  assign_bd_address -offset 0x00040000 -range 0x00040000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs cms_subsystem_0/s_axi_ctrl/Mem] -force
  assign_bd_address -offset 0x00000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs U200_ddr4_channel_0/ddr4_0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00001000 -range 0x00001000 -with_name SEG_ddr4_0_C0_REG_1 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs U200_ddr4_channel_1/ddr4_0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00002000 -range 0x00001000 -with_name SEG_ddr4_0_C0_REG_2 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs U200_ddr4_channel_2/ddr4_0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00003000 -range 0x00001000 -with_name SEG_ddr4_0_C0_REG_3 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs U200_ddr4_channel_3/ddr4_0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00004000 -range 0x00002000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs system_management_wiz_0/S_AXI_LITE/Reg] -force


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_U200_dma_ddr4_32G()

cr_bd_U200_dma_ddr4_32G ""
set_property REGISTERED_WITH_MANAGER "1" [get_files U200_dma_ddr4_32G.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files U200_dma_ddr4_32G.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse [list U200_dma_ddr4_32G.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/U200_dma_ddr4_32G/U200_dma_ddr4_32G.gen/sources_1/bd/U200_dma_ddr4_32G/hdl/U200_dma_ddr4_32G_wrapper.vhd" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list U200_dma_ddr4_32G.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


# Set 'U200_ddr4_channel_inst_0' fileset object
set obj [get_filesets U200_ddr4_channel_inst_0]
# Set 'U200_ddr4_channel_inst_0' fileset file properties for remote files
# None

# Set 'U200_ddr4_channel_inst_0' fileset file properties for local files
# None

# Set 'U200_ddr4_channel_inst_0' fileset properties
set obj [get_filesets U200_ddr4_channel_inst_0]
set_property -name "top" -value "U200_ddr4_channel_inst_0" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'U200_ddr4_channel_inst_1' fileset object
set obj [get_filesets U200_ddr4_channel_inst_1]
# Set 'U200_ddr4_channel_inst_1' fileset file properties for remote files
# None

# Set 'U200_ddr4_channel_inst_1' fileset file properties for local files
# None

# Set 'U200_ddr4_channel_inst_1' fileset properties
set obj [get_filesets U200_ddr4_channel_inst_1]
set_property -name "top" -value "U200_ddr4_channel_inst_1" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'U200_ddr4_channel_inst_2' fileset object
set obj [get_filesets U200_ddr4_channel_inst_2]
# Set 'U200_ddr4_channel_inst_2' fileset file properties for remote files
# None

# Set 'U200_ddr4_channel_inst_2' fileset file properties for local files
# None

# Set 'U200_ddr4_channel_inst_2' fileset properties
set obj [get_filesets U200_ddr4_channel_inst_2]
set_property -name "top" -value "U200_ddr4_channel_inst_2" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'U200_ddr4_channel_inst_3' fileset object
set obj [get_filesets U200_ddr4_channel_inst_3]
# Set 'U200_ddr4_channel_inst_3' fileset file properties for remote files
# None

# Set 'U200_ddr4_channel_inst_3' fileset file properties for local files
# None

# Set 'U200_ddr4_channel_inst_3' fileset properties
set obj [get_filesets U200_ddr4_channel_inst_3]
set_property -name "top" -value "U200_ddr4_channel_inst_3" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcu200-fsgd2104-2-e -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcu200-fsgd2104-2-e" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcu200-fsgd2104-2-e -flow {Vivado Implementation 2025} -strategy "Performance_ExtraTimingOpt" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_ExtraTimingOpt" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcu200-fsgd2104-2-e" -objects $obj
set_property -name "strategy" -value "Performance_ExtraTimingOpt" -objects $obj
set_property -name "steps.place_design.args.directive" -value "ExtraTimingOpt" -objects $obj
set_property -name "steps.phys_opt_design.args.directive" -value "Explore" -objects $obj
set_property -name "steps.route_design.args.directive" -value "NoTimingRelaxation" -objects $obj
set_property -name "steps.write_bitstream.tcl.post" -value "[file normalize "$origin_dir/../../multiple_boards/copy_bitstream_and_debug_probes.tcl"]" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
