# This is to prevent two critical warnings were reported for the implementation Methodology:
#
# a. TIMING-6: No Common Primary Clock Between Related Clocks
#    https://docs.amd.com/r/en-US/ug906-vivado-design-analysis/TIMING-6-No-Common-Primary-Clock-Between-Related-Clocks
#
#    The clocks ch0_txoutclk and clk_pl_0 are related (timed together) but they have no common primary clock.
#    The design could fail in hardware. To find a timing path between these clocks, run the following command:
#     report_timing -from [get_clocks ch0_txoutclk] -to [get_clocks clk_pl_0]
#
# b. TIMING-7: No Common Node Between Related Clocks
#    https://docs.amd.com/r/en-US/ug906-vivado-design-analysis/TIMING-7-No-Common-Node-Between-Related-Clocks
#
#    The clocks ch0_txoutclk and clk_pl_0 are related (timed together) but they have no common node.
#    The design could fail in hardware. To find a timing path between these clocks, run the following command:
#      report_timing -from [get_clocks ch0_txoutclk] -to [get_clocks clk_pl_0]
#
# clk_pl_0 is the free-running GT Wizard initialisation clock generated by the CIPS.
#
#
# @todo For reasonsnot understood this constraint file should be only enabled for implementation.
#       Otherwise Synthesis reports:
#         [Vivado 12-4739] set_clock_groups:No valid object(s) found for '-group [get_clocks ch0_txoutclk]'.  

set_clock_groups -group [get_clocks {clk_pl_0}] -group [get_clocks {ch0_txoutclk}] -asynchronous