#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'MRMAC_block_automation'
#
# Generated by Vivado on Sat Mar 21 14:55:21 GMT 2026
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "MRMAC_block_automation"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/MRMAC_block_automation"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcve2302-sfva784-1LP-e-S

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcve2302-sfva784-1LP-e-S" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcve2302-sfva784-1LP-e-S" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD MRMAC_block_automation
proc cr_bd_MRMAC_block_automation { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name MRMAC_block_automation

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:mrmac:3.2\
  xilinx.com:ip:gt_quad_base:1.1\
  xilinx.com:ip:util_ds_buf:2.2\
  xilinx.com:inline_hdl:ilconstant:1.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set GT_Serial [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gt_rtl:1.0 GT_Serial ]

  set CLK_IN_D [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 CLK_IN_D ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {156250000} \
   ] $CLK_IN_D

  set s_axi [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axi ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {32} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {32} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {0} \
   CONFIG.HAS_CACHE {0} \
   CONFIG.HAS_LOCK {0} \
   CONFIG.HAS_PROT {0} \
   CONFIG.HAS_QOS {0} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {0} \
   CONFIG.ID_WIDTH {0} \
   CONFIG.NUM_READ_OUTSTANDING {1} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {1} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4LITE} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $s_axi

  set ctl_tx_port0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:display_mrmac:mrmac_ctrl_ports:2.0 ctl_tx_port0 ]

  set ctl_tx_port1 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:display_mrmac:mrmac_ctrl_ports:2.0 ctl_tx_port1 ]

  set ctl_tx_port2 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:display_mrmac:mrmac_ctrl_ports:2.0 ctl_tx_port2 ]

  set ctl_tx_port3 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:display_mrmac:mrmac_ctrl_ports:2.0 ctl_tx_port3 ]

  set stat_tx_port0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_tx_port0 ]

  set stat_tx_port1 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_tx_port1 ]

  set stat_tx_port2 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_tx_port2 ]

  set stat_tx_port3 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_tx_port3 ]

  set stat_rx_port0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_rx_port0 ]

  set stat_rx_port1 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_rx_port1 ]

  set stat_rx_port2 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_rx_port2 ]

  set stat_rx_port3 [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 stat_rx_port3 ]

  set tx_preamblein [ create_bd_intf_port -mode Slave -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 tx_preamblein ]

  set rx_preambleout [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_mrmac:mrmac_statistics_ports:2.0 rx_preambleout ]

  set APB3_INTF [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:apb_rtl:1.0 APB3_INTF ]


  # Create ports
  set apb3clk_quad [ create_bd_port -dir I -type clk -freq_hz 200000000 apb3clk_quad ]
  set tx_axi_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 390625000 tx_axi_clk ]
  set rx_axi_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 390625000 rx_axi_clk ]
  set tx_core_reset [ create_bd_port -dir I -from 3 -to 0 -type rst tx_core_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $tx_core_reset
  set rx_core_reset [ create_bd_port -dir I -from 3 -to 0 -type rst rx_core_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $rx_core_reset
  set tx_serdes_reset [ create_bd_port -dir I -from 3 -to 0 -type rst tx_serdes_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $tx_serdes_reset
  set rx_serdes_reset [ create_bd_port -dir I -from 3 -to 0 -type rst rx_serdes_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $rx_serdes_reset
  set rx_flexif_reset [ create_bd_port -dir I -from 3 -to 0 -type rst rx_flexif_reset ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_HIGH} \
 ] $rx_flexif_reset
  set s_axi_aclk [ create_bd_port -dir I -type clk s_axi_aclk ]
  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {APB3_INTF:s_axi} \
 ] $s_axi_aclk
  set s_axi_aresetn [ create_bd_port -dir I -type rst s_axi_aresetn ]
  set tx_core_clk [ create_bd_port -dir I -from 3 -to 0 -type gt_usrclk tx_core_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {644531000} \
 ] $tx_core_clk
  set rx_core_clk [ create_bd_port -dir I -from 3 -to 0 -type gt_usrclk rx_core_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {644531000} \
 ] $rx_core_clk
  set rx_serdes_clk [ create_bd_port -dir I -from 3 -to 0 -type gt_usrclk rx_serdes_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {644531000} \
 ] $rx_serdes_clk
  set tx_alt_serdes_clk [ create_bd_port -dir I -from 3 -to 0 -type gt_usrclk tx_alt_serdes_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $tx_alt_serdes_clk
  set rx_alt_serdes_clk [ create_bd_port -dir I -from 3 -to 0 -type gt_usrclk rx_alt_serdes_clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $rx_alt_serdes_clk
  set tx_flexif_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 250000000 tx_flexif_clk ]
  set rx_flexif_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 250000000 rx_flexif_clk ]
  set tx_ts_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 250000000 tx_ts_clk ]
  set rx_ts_clk [ create_bd_port -dir I -from 3 -to 0 -type clk -freq_hz 250000000 rx_ts_clk ]
  set pm_tick [ create_bd_port -dir I -from 3 -to 0 pm_tick ]
  set gt_tx_reset_done_out [ create_bd_port -dir O -from 3 -to 0 gt_tx_reset_done_out ]
  set gt_rx_reset_done_out [ create_bd_port -dir O -from 3 -to 0 gt_rx_reset_done_out ]
  set gt_reset_all_in [ create_bd_port -dir I -from 3 -to 0 gt_reset_all_in ]
  set gtpowergood_in [ create_bd_port -dir I gtpowergood_in ]
  set ch0_tx_usr_clk [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch0_tx_usr_clk ]
  set ch1_tx_usr_clk [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch1_tx_usr_clk ]
  set ch0_rx_usr_clk [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch0_rx_usr_clk ]
  set ch1_rx_usr_clk [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch1_rx_usr_clk ]
  set ch0_tx_usr_clk2 [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch0_tx_usr_clk2 ]
  set ch1_tx_usr_clk2 [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch1_tx_usr_clk2 ]
  set ch0_rx_usr_clk2 [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch0_rx_usr_clk2 ]
  set ch1_rx_usr_clk2 [ create_bd_port -dir O -from 0 -to 0 -type gt_usrclk ch1_rx_usr_clk2 ]
  set tx_axis_tdata0 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata0 ]
  set tx_axis_tdata1 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata1 ]
  set tx_axis_tdata2 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata2 ]
  set tx_axis_tdata3 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata3 ]
  set tx_axis_tdata4 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata4 ]
  set tx_axis_tdata5 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata5 ]
  set tx_axis_tdata6 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata6 ]
  set tx_axis_tdata7 [ create_bd_port -dir I -from 63 -to 0 tx_axis_tdata7 ]
  set tx_axis_tkeep_user0 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user0 ]
  set tx_axis_tkeep_user1 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user1 ]
  set tx_axis_tkeep_user2 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user2 ]
  set tx_axis_tkeep_user3 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user3 ]
  set tx_axis_tkeep_user4 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user4 ]
  set tx_axis_tkeep_user5 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user5 ]
  set tx_axis_tkeep_user6 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user6 ]
  set tx_axis_tkeep_user7 [ create_bd_port -dir I -from 10 -to 0 tx_axis_tkeep_user7 ]
  set tx_axis_tready_0 [ create_bd_port -dir O tx_axis_tready_0 ]
  set tx_axis_tready_1 [ create_bd_port -dir O tx_axis_tready_1 ]
  set tx_axis_tready_2 [ create_bd_port -dir O tx_axis_tready_2 ]
  set tx_axis_tready_3 [ create_bd_port -dir O tx_axis_tready_3 ]
  set tx_axis_tlast_0 [ create_bd_port -dir I tx_axis_tlast_0 ]
  set tx_axis_tlast_1 [ create_bd_port -dir I tx_axis_tlast_1 ]
  set tx_axis_tlast_2 [ create_bd_port -dir I tx_axis_tlast_2 ]
  set tx_axis_tlast_3 [ create_bd_port -dir I tx_axis_tlast_3 ]
  set tx_axis_tvalid_0 [ create_bd_port -dir I tx_axis_tvalid_0 ]
  set tx_axis_tvalid_1 [ create_bd_port -dir I tx_axis_tvalid_1 ]
  set tx_axis_tvalid_2 [ create_bd_port -dir I tx_axis_tvalid_2 ]
  set tx_axis_tvalid_3 [ create_bd_port -dir I tx_axis_tvalid_3 ]
  set rx_axis_tdata0 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata0 ]
  set rx_axis_tdata1 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata1 ]
  set rx_axis_tdata2 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata2 ]
  set rx_axis_tdata3 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata3 ]
  set rx_axis_tdata4 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata4 ]
  set rx_axis_tdata5 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata5 ]
  set rx_axis_tdata6 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata6 ]
  set rx_axis_tdata7 [ create_bd_port -dir O -from 63 -to 0 rx_axis_tdata7 ]
  set rx_axis_tkeep_user0 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user0 ]
  set rx_axis_tkeep_user1 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user1 ]
  set rx_axis_tkeep_user2 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user2 ]
  set rx_axis_tkeep_user3 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user3 ]
  set rx_axis_tkeep_user4 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user4 ]
  set rx_axis_tkeep_user5 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user5 ]
  set rx_axis_tkeep_user6 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user6 ]
  set rx_axis_tkeep_user7 [ create_bd_port -dir O -from 10 -to 0 rx_axis_tkeep_user7 ]
  set rx_axis_tlast_0 [ create_bd_port -dir O rx_axis_tlast_0 ]
  set rx_axis_tlast_1 [ create_bd_port -dir O rx_axis_tlast_1 ]
  set rx_axis_tlast_2 [ create_bd_port -dir O rx_axis_tlast_2 ]
  set rx_axis_tlast_3 [ create_bd_port -dir O rx_axis_tlast_3 ]
  set rx_axis_tvalid_0 [ create_bd_port -dir O rx_axis_tvalid_0 ]
  set rx_axis_tvalid_1 [ create_bd_port -dir O rx_axis_tvalid_1 ]
  set rx_axis_tvalid_2 [ create_bd_port -dir O rx_axis_tvalid_2 ]
  set rx_axis_tvalid_3 [ create_bd_port -dir O rx_axis_tvalid_3 ]
  set gt_reset_tx_datapath_in [ create_bd_port -dir I -from 3 -to 0 gt_reset_tx_datapath_in ]
  set gt_reset_rx_datapath_in [ create_bd_port -dir I -from 3 -to 0 gt_reset_rx_datapath_in ]
  set pm_rdy [ create_bd_port -dir O -from 3 -to 0 pm_rdy ]
  set gtpowergood [ create_bd_port -dir O gtpowergood ]
  set ch0_rxusrclk [ create_bd_port -dir I -from 0 -to 0 -type gt_usrclk ch0_rxusrclk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $ch0_rxusrclk
  set ch0_txusrclk [ create_bd_port -dir I -from 0 -to 0 -type gt_usrclk ch0_txusrclk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $ch0_txusrclk
  set ch1_rxusrclk [ create_bd_port -dir I -from 0 -to 0 -type gt_usrclk ch1_rxusrclk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $ch1_rxusrclk
  set ch1_txusrclk [ create_bd_port -dir I -from 0 -to 0 -type gt_usrclk ch1_txusrclk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {322266000} \
 ] $ch1_txusrclk
  set ch0_loopback [ create_bd_port -dir I -from 2 -to 0 ch0_loopback ]
  set ch0_txrate [ create_bd_port -dir I -from 7 -to 0 ch0_txrate ]
  set ch0_rxrate [ create_bd_port -dir I -from 7 -to 0 ch0_rxrate ]
  set ch1_loopback [ create_bd_port -dir I -from 2 -to 0 ch1_loopback ]
  set ch1_txrate [ create_bd_port -dir I -from 7 -to 0 ch1_txrate ]
  set ch1_rxrate [ create_bd_port -dir I -from 7 -to 0 ch1_rxrate ]

  # Create instance: mrmac_0, and set properties
  set mrmac_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:mrmac:3.2 mrmac_0 ]
  set_property -dict [list \
    CONFIG.FEC_SLICE0_CFG_C0 {25G (IEEE 802.3 CL108)- RS(528 514)} \
    CONFIG.FEC_SLICE1_CFG_C0 {25G (IEEE 802.3 CL108)- RS(528 514)} \
    CONFIG.GT_REF_CLK_FREQ_C0 {156.25} \
    CONFIG.MAC_PORT0_RATE_C0 {25GE} \
    CONFIG.MAC_PORT2_RATE_C0 {N/U} \
    CONFIG.MAC_PORT3_RATE_C0 {N/U} \
    CONFIG.MRMAC_CONFIGURATION_TYPE {Dynamic Configuration} \
    CONFIG.MRMAC_DATA_PATH_INTERFACE_PORT0_C0 {Independent 128b Non-Segmented} \
    CONFIG.MRMAC_DATA_PATH_INTERFACE_PORT1_C0 {Independent 128b Non-Segmented} \
    CONFIG.MRMAC_IS_GT_WIZ_OLD {1} \
    CONFIG.MRMAC_MODE_C0 {MAC+PCS+FEC} \
    CONFIG.MRMAC_PRESET_C0 {Start from scratch} \
    CONFIG.MRMAC_SPEED_C0 {Mixed/Custom} \
  ] $mrmac_0


  # Create instance: gt_quad_base, and set properties
  set gt_quad_base [ create_bd_cell -type ip -vlnv xilinx.com:ip:gt_quad_base:1.1 gt_quad_base ]
  set_property -dict [list \
    CONFIG.APB3_CLK_FREQUENCY {200.0} \
    CONFIG.CHANNEL_ORDERING {/gt_quad_base/TX0_GT_IP_Interface MRMAC_block_automation_mrmac_0_0_0./mrmac_0/gt_tx_serdes_interface_0.0 /gt_quad_base/TX1_GT_IP_Interface MRMAC_block_automation_mrmac_0_0_1./mrmac_0/gt_tx_serdes_interface_1.1\
/gt_quad_base/RX0_GT_IP_Interface MRMAC_block_automation_mrmac_0_0_0./mrmac_0/gt_rx_serdes_interface_0.0 /gt_quad_base/RX1_GT_IP_Interface MRMAC_block_automation_mrmac_0_0_1./mrmac_0/gt_rx_serdes_interface_1.1}\
\
    CONFIG.GT_TYPE {GTYP} \
    CONFIG.PORTS_INFO_DICT {LANE_SEL_DICT {PROT0 {RX0 TX0} PROT1 {RX1 TX1} unconnected {RX2 RX3 TX2 TX3}} GT_TYPE GTYP REG_CONF_INTF APB3_INTF BOARD_PARAMETER { }} \
    CONFIG.PROT0_ENABLE {true} \
    CONFIG.PROT0_GT_DIRECTION {DUPLEX} \
    CONFIG.PROT0_LR0_SETTINGS {GT_DIRECTION DUPLEX TX_PAM_SEL NRZ TX_HD_EN 0 TX_GRAY_BYP true TX_GRAY_LITTLEENDIAN true TX_PRECODE_BYP true TX_PRECODE_LITTLEENDIAN false TX_LINE_RATE 25.78125 TX_PLL_TYPE\
LCPLL TX_REFCLK_FREQUENCY 156.25 TX_ACTUAL_REFCLK_FREQUENCY 156.250000000000 TX_FRACN_ENABLED true TX_FRACN_OVRD false TX_FRACN_NUMERATOR 0 TX_REFCLK_SOURCE R0 TX_DATA_ENCODING RAW TX_USER_DATA_WIDTH 80\
TX_INT_DATA_WIDTH 80 TX_BUFFER_MODE 1 TX_BUFFER_BYPASS_MODE Fast_Sync TX_PIPM_ENABLE false TX_OUTCLK_SOURCE TXPROGDIVCLK TXPROGDIV_FREQ_ENABLE true TXPROGDIV_FREQ_SOURCE LCPLL TXPROGDIV_FREQ_VAL 644.531\
TX_DIFF_SWING_EMPH_MODE CUSTOM TX_64B66B_SCRAMBLER false TX_64B66B_ENCODER false TX_64B66B_CRC false TX_RATE_GROUP A TX_LANE_DESKEW_HDMI_ENABLE false TX_BUFFER_RESET_ON_RATE_CHANGE ENABLE PRESET None RX_PAM_SEL\
NRZ RX_HD_EN 0 RX_GRAY_BYP true RX_GRAY_LITTLEENDIAN true RX_PRECODE_BYP true RX_PRECODE_LITTLEENDIAN false INTERNAL_PRESET None XPU_MODE 0 RX_LINE_RATE 25.78125 RX_PLL_TYPE LCPLL RX_REFCLK_FREQUENCY 156.25\
RX_ACTUAL_REFCLK_FREQUENCY 156.250000000000 RX_FRACN_ENABLED true RX_FRACN_OVRD false RX_FRACN_NUMERATOR 0 RX_REFCLK_SOURCE R0 RX_DATA_DECODING RAW RX_USER_DATA_WIDTH 80 RX_INT_DATA_WIDTH 80 RX_BUFFER_MODE\
1 RX_OUTCLK_SOURCE RXPROGDIVCLK RXPROGDIV_FREQ_ENABLE true RXPROGDIV_FREQ_SOURCE LCPLL RXPROGDIV_FREQ_VAL 644.531 RXRECCLK_FREQ_ENABLE true RXRECCLK_FREQ_VAL 644.531 INS_LOSS_NYQ 20 RX_EQ_MODE AUTO RX_COUPLING\
AC RX_TERMINATION PROGRAMMABLE RX_RATE_GROUP A RX_TERMINATION_PROG_VALUE 800 RX_PPM_OFFSET 200 RX_64B66B_DESCRAMBLER false RX_64B66B_DECODER false RX_64B66B_CRC false OOB_ENABLE false RX_COMMA_ALIGN_WORD\
1 RX_COMMA_SHOW_REALIGN_ENABLE true PCIE_ENABLE false RX_COMMA_P_ENABLE false RX_COMMA_M_ENABLE false RX_COMMA_DOUBLE_ENABLE false RX_COMMA_P_VAL 0101111100 RX_COMMA_M_VAL 1010000011 RX_COMMA_MASK 0000000000\
RX_SLIDE_MODE OFF RX_SSC_PPM 0 RX_CB_NUM_SEQ 0 RX_CB_LEN_SEQ 1 RX_CB_MAX_SKEW 1 RX_CB_MAX_LEVEL 1 RX_CB_MASK 00000000 RX_CB_VAL 00000000000000000000000000000000000000000000000000000000000000000000000000000000\
RX_CB_K 00000000 RX_CB_DISP 00000000 RX_CB_MASK_0_0 false RX_CB_VAL_0_0 0000000000 RX_CB_K_0_0 false RX_CB_DISP_0_0 false RX_CB_MASK_0_1 false RX_CB_VAL_0_1 0000000000 RX_CB_K_0_1 false RX_CB_DISP_0_1\
false RX_CB_MASK_0_2 false RX_CB_VAL_0_2 0000000000 RX_CB_K_0_2 false RX_CB_DISP_0_2 false RX_CB_MASK_0_3 false RX_CB_VAL_0_3 0000000000 RX_CB_K_0_3 false RX_CB_DISP_0_3 false RX_CB_MASK_1_0 false RX_CB_VAL_1_0\
0000000000 RX_CB_K_1_0 false RX_CB_DISP_1_0 false RX_CB_MASK_1_1 false RX_CB_VAL_1_1 0000000000 RX_CB_K_1_1 false RX_CB_DISP_1_1 false RX_CB_MASK_1_2 false RX_CB_VAL_1_2 0000000000 RX_CB_K_1_2 false RX_CB_DISP_1_2\
false RX_CB_MASK_1_3 false RX_CB_VAL_1_3 0000000000 RX_CB_K_1_3 false RX_CB_DISP_1_3 false RX_CC_NUM_SEQ 0 RX_CC_LEN_SEQ 1 RX_CC_PERIODICITY 5000 RX_CC_KEEP_IDLE DISABLE RX_CC_PRECEDENCE ENABLE RX_CC_REPEAT_WAIT\
0 RX_CC_MASK 00000000 RX_CC_VAL 00000000000000000000000000000000000000000000000000000000000000000000000000000000 RX_CC_K 00000000 RX_CC_DISP 00000000 RX_CC_MASK_0_0 false RX_CC_VAL_0_0 0000000000 RX_CC_K_0_0\
false RX_CC_DISP_0_0 false RX_CC_MASK_0_1 false RX_CC_VAL_0_1 0000000000 RX_CC_K_0_1 false RX_CC_DISP_0_1 false RX_CC_MASK_0_2 false RX_CC_VAL_0_2 0000000000 RX_CC_K_0_2 false RX_CC_DISP_0_2 false RX_CC_MASK_0_3\
false RX_CC_VAL_0_3 0000000000 RX_CC_K_0_3 false RX_CC_DISP_0_3 false RX_CC_MASK_1_0 false RX_CC_VAL_1_0 0000000000 RX_CC_K_1_0 false RX_CC_DISP_1_0 false RX_CC_MASK_1_1 false RX_CC_VAL_1_1 0000000000\
RX_CC_K_1_1 false RX_CC_DISP_1_1 false RX_CC_MASK_1_2 false RX_CC_VAL_1_2 0000000000 RX_CC_K_1_2 false RX_CC_DISP_1_2 false RX_CC_MASK_1_3 false RX_CC_VAL_1_3 0000000000 RX_CC_K_1_3 false RX_CC_DISP_1_3\
false PCIE_USERCLK2_FREQ 250 PCIE_USERCLK_FREQ 250 RX_JTOL_FC 10 RX_JTOL_LF_SLOPE -20 RX_BUFFER_BYPASS_MODE Fast_Sync RX_BUFFER_BYPASS_MODE_LANE MULTI RX_BUFFER_RESET_ON_CB_CHANGE ENABLE RX_BUFFER_RESET_ON_COMMAALIGN\
DISABLE RX_BUFFER_RESET_ON_RATE_CHANGE ENABLE RESET_SEQUENCE_INTERVAL 0 RX_COMMA_PRESET NONE RX_COMMA_VALID_ONLY 0 GT_TYPE GTYP} \
    CONFIG.PROT0_LR10_SETTINGS {NA NA} \
    CONFIG.PROT0_LR11_SETTINGS {NA NA} \
    CONFIG.PROT0_LR12_SETTINGS {NA NA} \
    CONFIG.PROT0_LR13_SETTINGS {NA NA} \
    CONFIG.PROT0_LR14_SETTINGS {NA NA} \
    CONFIG.PROT0_LR15_SETTINGS {NA NA} \
    CONFIG.PROT0_LR1_SETTINGS {NA NA} \
    CONFIG.PROT0_LR2_SETTINGS {NA NA} \
    CONFIG.PROT0_LR3_SETTINGS {NA NA} \
    CONFIG.PROT0_LR4_SETTINGS {NA NA} \
    CONFIG.PROT0_LR5_SETTINGS {NA NA} \
    CONFIG.PROT0_LR6_SETTINGS {NA NA} \
    CONFIG.PROT0_LR7_SETTINGS {NA NA} \
    CONFIG.PROT0_LR8_SETTINGS {NA NA} \
    CONFIG.PROT0_LR9_SETTINGS {NA NA} \
    CONFIG.PROT0_NO_OF_LANES {1} \
    CONFIG.PROT0_RX_MASTERCLK_SRC {RX0} \
    CONFIG.PROT0_TX_MASTERCLK_SRC {TX0} \
    CONFIG.PROT1_ENABLE {true} \
    CONFIG.PROT1_GT_DIRECTION {DUPLEX} \
    CONFIG.PROT1_LR0_SETTINGS {GT_DIRECTION DUPLEX TX_PAM_SEL NRZ TX_HD_EN 0 TX_GRAY_BYP true TX_GRAY_LITTLEENDIAN true TX_PRECODE_BYP true TX_PRECODE_LITTLEENDIAN false TX_LINE_RATE 25.78125 TX_PLL_TYPE\
LCPLL TX_REFCLK_FREQUENCY 156.25 TX_ACTUAL_REFCLK_FREQUENCY 156.250000000000 TX_FRACN_ENABLED true TX_FRACN_OVRD false TX_FRACN_NUMERATOR 0 TX_REFCLK_SOURCE R0 TX_DATA_ENCODING RAW TX_USER_DATA_WIDTH 80\
TX_INT_DATA_WIDTH 80 TX_BUFFER_MODE 1 TX_BUFFER_BYPASS_MODE Fast_Sync TX_PIPM_ENABLE false TX_OUTCLK_SOURCE TXPROGDIVCLK TXPROGDIV_FREQ_ENABLE true TXPROGDIV_FREQ_SOURCE LCPLL TXPROGDIV_FREQ_VAL 644.531\
TX_DIFF_SWING_EMPH_MODE CUSTOM TX_64B66B_SCRAMBLER false TX_64B66B_ENCODER false TX_64B66B_CRC false TX_RATE_GROUP A TX_LANE_DESKEW_HDMI_ENABLE false TX_BUFFER_RESET_ON_RATE_CHANGE ENABLE PRESET None RX_PAM_SEL\
NRZ RX_HD_EN 0 RX_GRAY_BYP true RX_GRAY_LITTLEENDIAN true RX_PRECODE_BYP true RX_PRECODE_LITTLEENDIAN false INTERNAL_PRESET None XPU_MODE 0 RX_LINE_RATE 25.78125 RX_PLL_TYPE LCPLL RX_REFCLK_FREQUENCY 156.25\
RX_ACTUAL_REFCLK_FREQUENCY 156.250000000000 RX_FRACN_ENABLED true RX_FRACN_OVRD false RX_FRACN_NUMERATOR 0 RX_REFCLK_SOURCE R0 RX_DATA_DECODING RAW RX_USER_DATA_WIDTH 80 RX_INT_DATA_WIDTH 80 RX_BUFFER_MODE\
1 RX_OUTCLK_SOURCE RXPROGDIVCLK RXPROGDIV_FREQ_ENABLE true RXPROGDIV_FREQ_SOURCE LCPLL RXPROGDIV_FREQ_VAL 644.531 RXRECCLK_FREQ_ENABLE true RXRECCLK_FREQ_VAL 644.531 INS_LOSS_NYQ 20 RX_EQ_MODE AUTO RX_COUPLING\
AC RX_TERMINATION PROGRAMMABLE RX_RATE_GROUP A RX_TERMINATION_PROG_VALUE 800 RX_PPM_OFFSET 200 RX_64B66B_DESCRAMBLER false RX_64B66B_DECODER false RX_64B66B_CRC false OOB_ENABLE false RX_COMMA_ALIGN_WORD\
1 RX_COMMA_SHOW_REALIGN_ENABLE true PCIE_ENABLE false RX_COMMA_P_ENABLE false RX_COMMA_M_ENABLE false RX_COMMA_DOUBLE_ENABLE false RX_COMMA_P_VAL 0101111100 RX_COMMA_M_VAL 1010000011 RX_COMMA_MASK 0000000000\
RX_SLIDE_MODE OFF RX_SSC_PPM 0 RX_CB_NUM_SEQ 0 RX_CB_LEN_SEQ 1 RX_CB_MAX_SKEW 1 RX_CB_MAX_LEVEL 1 RX_CB_MASK 00000000 RX_CB_VAL 00000000000000000000000000000000000000000000000000000000000000000000000000000000\
RX_CB_K 00000000 RX_CB_DISP 00000000 RX_CB_MASK_0_0 false RX_CB_VAL_0_0 0000000000 RX_CB_K_0_0 false RX_CB_DISP_0_0 false RX_CB_MASK_0_1 false RX_CB_VAL_0_1 0000000000 RX_CB_K_0_1 false RX_CB_DISP_0_1\
false RX_CB_MASK_0_2 false RX_CB_VAL_0_2 0000000000 RX_CB_K_0_2 false RX_CB_DISP_0_2 false RX_CB_MASK_0_3 false RX_CB_VAL_0_3 0000000000 RX_CB_K_0_3 false RX_CB_DISP_0_3 false RX_CB_MASK_1_0 false RX_CB_VAL_1_0\
0000000000 RX_CB_K_1_0 false RX_CB_DISP_1_0 false RX_CB_MASK_1_1 false RX_CB_VAL_1_1 0000000000 RX_CB_K_1_1 false RX_CB_DISP_1_1 false RX_CB_MASK_1_2 false RX_CB_VAL_1_2 0000000000 RX_CB_K_1_2 false RX_CB_DISP_1_2\
false RX_CB_MASK_1_3 false RX_CB_VAL_1_3 0000000000 RX_CB_K_1_3 false RX_CB_DISP_1_3 false RX_CC_NUM_SEQ 0 RX_CC_LEN_SEQ 1 RX_CC_PERIODICITY 5000 RX_CC_KEEP_IDLE DISABLE RX_CC_PRECEDENCE ENABLE RX_CC_REPEAT_WAIT\
0 RX_CC_MASK 00000000 RX_CC_VAL 00000000000000000000000000000000000000000000000000000000000000000000000000000000 RX_CC_K 00000000 RX_CC_DISP 00000000 RX_CC_MASK_0_0 false RX_CC_VAL_0_0 0000000000 RX_CC_K_0_0\
false RX_CC_DISP_0_0 false RX_CC_MASK_0_1 false RX_CC_VAL_0_1 0000000000 RX_CC_K_0_1 false RX_CC_DISP_0_1 false RX_CC_MASK_0_2 false RX_CC_VAL_0_2 0000000000 RX_CC_K_0_2 false RX_CC_DISP_0_2 false RX_CC_MASK_0_3\
false RX_CC_VAL_0_3 0000000000 RX_CC_K_0_3 false RX_CC_DISP_0_3 false RX_CC_MASK_1_0 false RX_CC_VAL_1_0 0000000000 RX_CC_K_1_0 false RX_CC_DISP_1_0 false RX_CC_MASK_1_1 false RX_CC_VAL_1_1 0000000000\
RX_CC_K_1_1 false RX_CC_DISP_1_1 false RX_CC_MASK_1_2 false RX_CC_VAL_1_2 0000000000 RX_CC_K_1_2 false RX_CC_DISP_1_2 false RX_CC_MASK_1_3 false RX_CC_VAL_1_3 0000000000 RX_CC_K_1_3 false RX_CC_DISP_1_3\
false PCIE_USERCLK2_FREQ 250 PCIE_USERCLK_FREQ 250 RX_JTOL_FC 10 RX_JTOL_LF_SLOPE -20 RX_BUFFER_BYPASS_MODE Fast_Sync RX_BUFFER_BYPASS_MODE_LANE MULTI RX_BUFFER_RESET_ON_CB_CHANGE ENABLE RX_BUFFER_RESET_ON_COMMAALIGN\
DISABLE RX_BUFFER_RESET_ON_RATE_CHANGE ENABLE RESET_SEQUENCE_INTERVAL 0 RX_COMMA_PRESET NONE RX_COMMA_VALID_ONLY 0 GT_TYPE GTYP} \
    CONFIG.PROT1_LR10_SETTINGS {NA NA} \
    CONFIG.PROT1_LR11_SETTINGS {NA NA} \
    CONFIG.PROT1_LR12_SETTINGS {NA NA} \
    CONFIG.PROT1_LR13_SETTINGS {NA NA} \
    CONFIG.PROT1_LR14_SETTINGS {NA NA} \
    CONFIG.PROT1_LR15_SETTINGS {NA NA} \
    CONFIG.PROT1_LR1_SETTINGS {NA NA} \
    CONFIG.PROT1_LR2_SETTINGS {NA NA} \
    CONFIG.PROT1_LR3_SETTINGS {NA NA} \
    CONFIG.PROT1_LR4_SETTINGS {NA NA} \
    CONFIG.PROT1_LR5_SETTINGS {NA NA} \
    CONFIG.PROT1_LR6_SETTINGS {NA NA} \
    CONFIG.PROT1_LR7_SETTINGS {NA NA} \
    CONFIG.PROT1_LR8_SETTINGS {NA NA} \
    CONFIG.PROT1_LR9_SETTINGS {NA NA} \
    CONFIG.PROT1_NO_OF_LANES {1} \
    CONFIG.PROT1_RX_MASTERCLK_SRC {RX1} \
    CONFIG.PROT1_TX_MASTERCLK_SRC {TX1} \
    CONFIG.QUAD_USAGE {TX_QUAD_CH {TXQuad_0_/gt_quad_base {/gt_quad_base MRMAC_block_automation_mrmac_0_0_0.IP_CH0,MRMAC_block_automation_mrmac_0_0_1.IP_CH1,undef,undef MSTRCLK 1,1,0,0 IS_CURRENT_QUAD\
1}} RX_QUAD_CH {RXQuad_0_/gt_quad_base {/gt_quad_base MRMAC_block_automation_mrmac_0_0_0.IP_CH0,MRMAC_block_automation_mrmac_0_0_1.IP_CH1,undef,undef MSTRCLK 1,1,0,0 IS_CURRENT_QUAD 1}}} \
    CONFIG.REFCLK_LIST {{/CLK_IN_D_clk_p[0]}} \
    CONFIG.REFCLK_STRING {HSCLK0_LCPLLGTREFCLK0 refclk_PROT0_R0_PROT1_R0_156.25_MHz_unique1} \
    CONFIG.RX0_LANE_SEL {PROT0} \
    CONFIG.RX1_LANE_SEL {PROT1} \
    CONFIG.RX2_LANE_SEL {unconnected} \
    CONFIG.RX3_LANE_SEL {unconnected} \
    CONFIG.TX0_LANE_SEL {PROT0} \
    CONFIG.TX1_LANE_SEL {PROT1} \
    CONFIG.TX2_LANE_SEL {unconnected} \
    CONFIG.TX3_LANE_SEL {unconnected} \
  ] $gt_quad_base

  set_property -dict [list \
    CONFIG.APB3_CLK_FREQUENCY.VALUE_MODE {auto} \
    CONFIG.CHANNEL_ORDERING.VALUE_MODE {auto} \
    CONFIG.GT_TYPE.VALUE_MODE {auto} \
    CONFIG.PROT0_ENABLE.VALUE_MODE {auto} \
    CONFIG.PROT0_GT_DIRECTION.VALUE_MODE {auto} \
    CONFIG.PROT0_LR0_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR10_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR11_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR12_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR13_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR14_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR15_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR1_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR2_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR3_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR4_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR5_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR6_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR7_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR8_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_LR9_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT0_NO_OF_LANES.VALUE_MODE {auto} \
    CONFIG.PROT0_RX_MASTERCLK_SRC.VALUE_MODE {auto} \
    CONFIG.PROT0_TX_MASTERCLK_SRC.VALUE_MODE {auto} \
    CONFIG.PROT1_ENABLE.VALUE_MODE {auto} \
    CONFIG.PROT1_GT_DIRECTION.VALUE_MODE {auto} \
    CONFIG.PROT1_LR0_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR10_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR11_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR12_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR13_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR14_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR15_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR1_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR2_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR3_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR4_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR5_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR6_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR7_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR8_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_LR9_SETTINGS.VALUE_MODE {auto} \
    CONFIG.PROT1_NO_OF_LANES.VALUE_MODE {auto} \
    CONFIG.PROT1_RX_MASTERCLK_SRC.VALUE_MODE {auto} \
    CONFIG.PROT1_TX_MASTERCLK_SRC.VALUE_MODE {auto} \
    CONFIG.QUAD_USAGE.VALUE_MODE {auto} \
    CONFIG.REFCLK_LIST.VALUE_MODE {auto} \
    CONFIG.RX0_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.RX1_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.RX2_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.RX3_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.TX0_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.TX1_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.TX2_LANE_SEL.VALUE_MODE {auto} \
    CONFIG.TX3_LANE_SEL.VALUE_MODE {auto} \
  ] $gt_quad_base


  # Create instance: util_ds_buf_0, and set properties
  set util_ds_buf_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 util_ds_buf_0 ]
  set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} $util_ds_buf_0


  # Create instance: xlconst_mbufg_0, and set properties
  set xlconst_mbufg_0 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconstant:1.0 xlconst_mbufg_0 ]
  set_property -dict [list \
    CONFIG.CONST_VAL {1} \
    CONFIG.CONST_WIDTH {1} \
  ] $xlconst_mbufg_0


  # Create instance: mbufg_gt_0, and set properties
  set mbufg_gt_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 mbufg_gt_0 ]
  set_property -dict [list \
    CONFIG.C_BUFG_GT_SYNC {true} \
    CONFIG.C_BUF_TYPE {MBUFG_GT} \
  ] $mbufg_gt_0


  # Create instance: mbufg_gt_0_1, and set properties
  set mbufg_gt_0_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 mbufg_gt_0_1 ]
  set_property -dict [list \
    CONFIG.C_BUFG_GT_SYNC {true} \
    CONFIG.C_BUF_TYPE {MBUFG_GT} \
  ] $mbufg_gt_0_1


  # Create instance: mbufg_gt_1, and set properties
  set mbufg_gt_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 mbufg_gt_1 ]
  set_property -dict [list \
    CONFIG.C_BUFG_GT_SYNC {true} \
    CONFIG.C_BUF_TYPE {MBUFG_GT} \
  ] $mbufg_gt_1


  # Create instance: mbufg_gt_1_1, and set properties
  set mbufg_gt_1_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 mbufg_gt_1_1 ]
  set_property -dict [list \
    CONFIG.C_BUFG_GT_SYNC {true} \
    CONFIG.C_BUF_TYPE {MBUFG_GT} \
  ] $mbufg_gt_1_1


  # Create interface connections
  connect_bd_intf_net -intf_net APB3_INTF_1 [get_bd_intf_ports APB3_INTF] [get_bd_intf_pins gt_quad_base/APB3_INTF]
  connect_bd_intf_net -intf_net CLK_IN_D_1 [get_bd_intf_ports CLK_IN_D] [get_bd_intf_pins util_ds_buf_0/CLK_IN_D]
  connect_bd_intf_net -intf_net ctl_tx_port0_1 [get_bd_intf_ports ctl_tx_port0] [get_bd_intf_pins mrmac_0/ctl_tx_port0]
  connect_bd_intf_net -intf_net ctl_tx_port1_1 [get_bd_intf_ports ctl_tx_port1] [get_bd_intf_pins mrmac_0/ctl_tx_port1]
  connect_bd_intf_net -intf_net ctl_tx_port2_1 [get_bd_intf_ports ctl_tx_port2] [get_bd_intf_pins mrmac_0/ctl_tx_port2]
  connect_bd_intf_net -intf_net ctl_tx_port3_1 [get_bd_intf_ports ctl_tx_port3] [get_bd_intf_pins mrmac_0/ctl_tx_port3]
  connect_bd_intf_net -intf_net gt_quad_base_GT_Serial [get_bd_intf_pins gt_quad_base/GT_Serial] [get_bd_intf_ports GT_Serial]
  connect_bd_intf_net -intf_net mrmac_0_gt_rx_serdes_interface_0 [get_bd_intf_pins mrmac_0/gt_rx_serdes_interface_0] [get_bd_intf_pins gt_quad_base/RX0_GT_IP_Interface]
  connect_bd_intf_net -intf_net mrmac_0_gt_rx_serdes_interface_1 [get_bd_intf_pins mrmac_0/gt_rx_serdes_interface_1] [get_bd_intf_pins gt_quad_base/RX1_GT_IP_Interface]
  connect_bd_intf_net -intf_net mrmac_0_gt_tx_serdes_interface_0 [get_bd_intf_pins mrmac_0/gt_tx_serdes_interface_0] [get_bd_intf_pins gt_quad_base/TX0_GT_IP_Interface]
  connect_bd_intf_net -intf_net mrmac_0_gt_tx_serdes_interface_1 [get_bd_intf_pins mrmac_0/gt_tx_serdes_interface_1] [get_bd_intf_pins gt_quad_base/TX1_GT_IP_Interface]
  connect_bd_intf_net -intf_net mrmac_0_rx_preambleout [get_bd_intf_ports rx_preambleout] [get_bd_intf_pins mrmac_0/rx_preambleout]
  connect_bd_intf_net -intf_net mrmac_0_stat_rx_port0 [get_bd_intf_ports stat_rx_port0] [get_bd_intf_pins mrmac_0/stat_rx_port0]
  connect_bd_intf_net -intf_net mrmac_0_stat_rx_port1 [get_bd_intf_ports stat_rx_port1] [get_bd_intf_pins mrmac_0/stat_rx_port1]
  connect_bd_intf_net -intf_net mrmac_0_stat_rx_port2 [get_bd_intf_ports stat_rx_port2] [get_bd_intf_pins mrmac_0/stat_rx_port2]
  connect_bd_intf_net -intf_net mrmac_0_stat_rx_port3 [get_bd_intf_ports stat_rx_port3] [get_bd_intf_pins mrmac_0/stat_rx_port3]
  connect_bd_intf_net -intf_net mrmac_0_stat_tx_port0 [get_bd_intf_ports stat_tx_port0] [get_bd_intf_pins mrmac_0/stat_tx_port0]
  connect_bd_intf_net -intf_net mrmac_0_stat_tx_port1 [get_bd_intf_ports stat_tx_port1] [get_bd_intf_pins mrmac_0/stat_tx_port1]
  connect_bd_intf_net -intf_net mrmac_0_stat_tx_port2 [get_bd_intf_ports stat_tx_port2] [get_bd_intf_pins mrmac_0/stat_tx_port2]
  connect_bd_intf_net -intf_net mrmac_0_stat_tx_port3 [get_bd_intf_ports stat_tx_port3] [get_bd_intf_pins mrmac_0/stat_tx_port3]
  connect_bd_intf_net -intf_net s_axi_1 [get_bd_intf_ports s_axi] [get_bd_intf_pins mrmac_0/s_axi]
  connect_bd_intf_net -intf_net tx_preamblein_1 [get_bd_intf_ports tx_preamblein] [get_bd_intf_pins mrmac_0/tx_preamblein]

  # Create port connections
  connect_bd_net -net apb3clk_quad_1  [get_bd_ports apb3clk_quad] \
  [get_bd_pins gt_quad_base/apb3clk]
  connect_bd_net -net ch0_loopback_1  [get_bd_ports ch0_loopback] \
  [get_bd_pins gt_quad_base/ch0_loopback]
  connect_bd_net -net ch0_rxrate_1  [get_bd_ports ch0_rxrate] \
  [get_bd_pins gt_quad_base/ch0_rxrate]
  connect_bd_net -net ch0_rxusrclk_1  [get_bd_ports ch0_rxusrclk] \
  [get_bd_pins gt_quad_base/ch0_rxusrclk]
  connect_bd_net -net ch0_txrate_1  [get_bd_ports ch0_txrate] \
  [get_bd_pins gt_quad_base/ch0_txrate]
  connect_bd_net -net ch0_txusrclk_1  [get_bd_ports ch0_txusrclk] \
  [get_bd_pins gt_quad_base/ch0_txusrclk]
  connect_bd_net -net ch1_loopback_1  [get_bd_ports ch1_loopback] \
  [get_bd_pins gt_quad_base/ch1_loopback]
  connect_bd_net -net ch1_rxrate_1  [get_bd_ports ch1_rxrate] \
  [get_bd_pins gt_quad_base/ch1_rxrate]
  connect_bd_net -net ch1_rxusrclk_1  [get_bd_ports ch1_rxusrclk] \
  [get_bd_pins gt_quad_base/ch1_rxusrclk]
  connect_bd_net -net ch1_txrate_1  [get_bd_ports ch1_txrate] \
  [get_bd_pins gt_quad_base/ch1_txrate]
  connect_bd_net -net ch1_txusrclk_1  [get_bd_ports ch1_txusrclk] \
  [get_bd_pins gt_quad_base/ch1_txusrclk]
  connect_bd_net -net gt_quad_base_ch0_rxoutclk  [get_bd_pins gt_quad_base/ch0_rxoutclk] \
  [get_bd_pins mbufg_gt_1/MBUFG_GT_I]
  connect_bd_net -net gt_quad_base_ch0_txoutclk  [get_bd_pins gt_quad_base/ch0_txoutclk] \
  [get_bd_pins mbufg_gt_0/MBUFG_GT_I]
  connect_bd_net -net gt_quad_base_ch1_rxoutclk  [get_bd_pins gt_quad_base/ch1_rxoutclk] \
  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_I]
  connect_bd_net -net gt_quad_base_ch1_txoutclk  [get_bd_pins gt_quad_base/ch1_txoutclk] \
  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_I]
  connect_bd_net -net gt_quad_base_gtpowergood  [get_bd_pins gt_quad_base/gtpowergood] \
  [get_bd_ports gtpowergood]
  connect_bd_net -net gt_reset_all_in_1  [get_bd_ports gt_reset_all_in] \
  [get_bd_pins mrmac_0/gt_reset_all_in]
  connect_bd_net -net gt_reset_rx_datapath_in_1  [get_bd_ports gt_reset_rx_datapath_in] \
  [get_bd_pins mrmac_0/gt_reset_rx_datapath_in]
  connect_bd_net -net gt_reset_tx_datapath_in_1  [get_bd_ports gt_reset_tx_datapath_in] \
  [get_bd_pins mrmac_0/gt_reset_tx_datapath_in]
  connect_bd_net -net gtpowergood_in_1  [get_bd_ports gtpowergood_in] \
  [get_bd_pins mrmac_0/gtpowergood_in]
  connect_bd_net -net mbufg_gt_0_1_MBUFG_GT_O1  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_O1] \
  [get_bd_ports ch1_tx_usr_clk]
  connect_bd_net -net mbufg_gt_0_1_MBUFG_GT_O2  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_O2] \
  [get_bd_ports ch1_tx_usr_clk2]
  connect_bd_net -net mbufg_gt_0_MBUFG_GT_O1  [get_bd_pins mbufg_gt_0/MBUFG_GT_O1] \
  [get_bd_ports ch0_tx_usr_clk]
  connect_bd_net -net mbufg_gt_0_MBUFG_GT_O2  [get_bd_pins mbufg_gt_0/MBUFG_GT_O2] \
  [get_bd_ports ch0_tx_usr_clk2]
  connect_bd_net -net mbufg_gt_1_1_MBUFG_GT_O1  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_O1] \
  [get_bd_ports ch1_rx_usr_clk]
  connect_bd_net -net mbufg_gt_1_1_MBUFG_GT_O2  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_O2] \
  [get_bd_ports ch1_rx_usr_clk2]
  connect_bd_net -net mbufg_gt_1_MBUFG_GT_O1  [get_bd_pins mbufg_gt_1/MBUFG_GT_O1] \
  [get_bd_ports ch0_rx_usr_clk]
  connect_bd_net -net mbufg_gt_1_MBUFG_GT_O2  [get_bd_pins mbufg_gt_1/MBUFG_GT_O2] \
  [get_bd_ports ch0_rx_usr_clk2]
  connect_bd_net -net mrmac_0_gt_rx_reset_done_out  [get_bd_pins mrmac_0/gt_rx_reset_done_out] \
  [get_bd_ports gt_rx_reset_done_out]
  connect_bd_net -net mrmac_0_gt_tx_reset_done_out  [get_bd_pins mrmac_0/gt_tx_reset_done_out] \
  [get_bd_ports gt_tx_reset_done_out]
  connect_bd_net -net mrmac_0_pm_rdy  [get_bd_pins mrmac_0/pm_rdy] \
  [get_bd_ports pm_rdy]
  connect_bd_net -net mrmac_0_rx_axis_tdata0  [get_bd_pins mrmac_0/rx_axis_tdata0] \
  [get_bd_ports rx_axis_tdata0]
  connect_bd_net -net mrmac_0_rx_axis_tdata1  [get_bd_pins mrmac_0/rx_axis_tdata1] \
  [get_bd_ports rx_axis_tdata1]
  connect_bd_net -net mrmac_0_rx_axis_tdata2  [get_bd_pins mrmac_0/rx_axis_tdata2] \
  [get_bd_ports rx_axis_tdata2]
  connect_bd_net -net mrmac_0_rx_axis_tdata3  [get_bd_pins mrmac_0/rx_axis_tdata3] \
  [get_bd_ports rx_axis_tdata3]
  connect_bd_net -net mrmac_0_rx_axis_tdata4  [get_bd_pins mrmac_0/rx_axis_tdata4] \
  [get_bd_ports rx_axis_tdata4]
  connect_bd_net -net mrmac_0_rx_axis_tdata5  [get_bd_pins mrmac_0/rx_axis_tdata5] \
  [get_bd_ports rx_axis_tdata5]
  connect_bd_net -net mrmac_0_rx_axis_tdata6  [get_bd_pins mrmac_0/rx_axis_tdata6] \
  [get_bd_ports rx_axis_tdata6]
  connect_bd_net -net mrmac_0_rx_axis_tdata7  [get_bd_pins mrmac_0/rx_axis_tdata7] \
  [get_bd_ports rx_axis_tdata7]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user0  [get_bd_pins mrmac_0/rx_axis_tkeep_user0] \
  [get_bd_ports rx_axis_tkeep_user0]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user1  [get_bd_pins mrmac_0/rx_axis_tkeep_user1] \
  [get_bd_ports rx_axis_tkeep_user1]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user2  [get_bd_pins mrmac_0/rx_axis_tkeep_user2] \
  [get_bd_ports rx_axis_tkeep_user2]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user3  [get_bd_pins mrmac_0/rx_axis_tkeep_user3] \
  [get_bd_ports rx_axis_tkeep_user3]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user4  [get_bd_pins mrmac_0/rx_axis_tkeep_user4] \
  [get_bd_ports rx_axis_tkeep_user4]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user5  [get_bd_pins mrmac_0/rx_axis_tkeep_user5] \
  [get_bd_ports rx_axis_tkeep_user5]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user6  [get_bd_pins mrmac_0/rx_axis_tkeep_user6] \
  [get_bd_ports rx_axis_tkeep_user6]
  connect_bd_net -net mrmac_0_rx_axis_tkeep_user7  [get_bd_pins mrmac_0/rx_axis_tkeep_user7] \
  [get_bd_ports rx_axis_tkeep_user7]
  connect_bd_net -net mrmac_0_rx_axis_tlast_0  [get_bd_pins mrmac_0/rx_axis_tlast_0] \
  [get_bd_ports rx_axis_tlast_0]
  connect_bd_net -net mrmac_0_rx_axis_tlast_1  [get_bd_pins mrmac_0/rx_axis_tlast_1] \
  [get_bd_ports rx_axis_tlast_1]
  connect_bd_net -net mrmac_0_rx_axis_tlast_2  [get_bd_pins mrmac_0/rx_axis_tlast_2] \
  [get_bd_ports rx_axis_tlast_2]
  connect_bd_net -net mrmac_0_rx_axis_tlast_3  [get_bd_pins mrmac_0/rx_axis_tlast_3] \
  [get_bd_ports rx_axis_tlast_3]
  connect_bd_net -net mrmac_0_rx_axis_tvalid_0  [get_bd_pins mrmac_0/rx_axis_tvalid_0] \
  [get_bd_ports rx_axis_tvalid_0]
  connect_bd_net -net mrmac_0_rx_axis_tvalid_1  [get_bd_pins mrmac_0/rx_axis_tvalid_1] \
  [get_bd_ports rx_axis_tvalid_1]
  connect_bd_net -net mrmac_0_rx_axis_tvalid_2  [get_bd_pins mrmac_0/rx_axis_tvalid_2] \
  [get_bd_ports rx_axis_tvalid_2]
  connect_bd_net -net mrmac_0_rx_axis_tvalid_3  [get_bd_pins mrmac_0/rx_axis_tvalid_3] \
  [get_bd_ports rx_axis_tvalid_3]
  connect_bd_net -net mrmac_0_rx_clr_out_0  [get_bd_pins mrmac_0/rx_clr_out_0] \
  [get_bd_pins mbufg_gt_1/MBUFG_GT_CLR]
  connect_bd_net -net mrmac_0_rx_clr_out_1  [get_bd_pins mrmac_0/rx_clr_out_1] \
  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_CLR]
  connect_bd_net -net mrmac_0_rx_clrb_leaf_out_0  [get_bd_pins mrmac_0/rx_clrb_leaf_out_0] \
  [get_bd_pins mbufg_gt_1/MBUFG_GT_CLRB_LEAF]
  connect_bd_net -net mrmac_0_rx_clrb_leaf_out_1  [get_bd_pins mrmac_0/rx_clrb_leaf_out_1] \
  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_CLRB_LEAF]
  connect_bd_net -net mrmac_0_tx_axis_tready_0  [get_bd_pins mrmac_0/tx_axis_tready_0] \
  [get_bd_ports tx_axis_tready_0]
  connect_bd_net -net mrmac_0_tx_axis_tready_1  [get_bd_pins mrmac_0/tx_axis_tready_1] \
  [get_bd_ports tx_axis_tready_1]
  connect_bd_net -net mrmac_0_tx_axis_tready_2  [get_bd_pins mrmac_0/tx_axis_tready_2] \
  [get_bd_ports tx_axis_tready_2]
  connect_bd_net -net mrmac_0_tx_axis_tready_3  [get_bd_pins mrmac_0/tx_axis_tready_3] \
  [get_bd_ports tx_axis_tready_3]
  connect_bd_net -net mrmac_0_tx_clr_out_0  [get_bd_pins mrmac_0/tx_clr_out_0] \
  [get_bd_pins mbufg_gt_0/MBUFG_GT_CLR]
  connect_bd_net -net mrmac_0_tx_clr_out_1  [get_bd_pins mrmac_0/tx_clr_out_1] \
  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_CLR]
  connect_bd_net -net mrmac_0_tx_clrb_leaf_out_0  [get_bd_pins mrmac_0/tx_clrb_leaf_out_0] \
  [get_bd_pins mbufg_gt_0/MBUFG_GT_CLRB_LEAF]
  connect_bd_net -net mrmac_0_tx_clrb_leaf_out_1  [get_bd_pins mrmac_0/tx_clrb_leaf_out_1] \
  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_CLRB_LEAF]
  connect_bd_net -net pm_tick_1  [get_bd_ports pm_tick] \
  [get_bd_pins mrmac_0/pm_tick]
  connect_bd_net -net rx_alt_serdes_clk_1  [get_bd_ports rx_alt_serdes_clk] \
  [get_bd_pins mrmac_0/rx_alt_serdes_clk]
  connect_bd_net -net rx_axi_clk_1  [get_bd_ports rx_axi_clk] \
  [get_bd_pins mrmac_0/rx_axi_clk]
  connect_bd_net -net rx_core_clk_1  [get_bd_ports rx_core_clk] \
  [get_bd_pins mrmac_0/rx_core_clk]
  connect_bd_net -net rx_core_reset_1  [get_bd_ports rx_core_reset] \
  [get_bd_pins mrmac_0/rx_core_reset]
  connect_bd_net -net rx_flexif_clk_1  [get_bd_ports rx_flexif_clk] \
  [get_bd_pins mrmac_0/rx_flexif_clk]
  connect_bd_net -net rx_flexif_reset_1  [get_bd_ports rx_flexif_reset] \
  [get_bd_pins mrmac_0/rx_flexif_reset]
  connect_bd_net -net rx_serdes_clk_1  [get_bd_ports rx_serdes_clk] \
  [get_bd_pins mrmac_0/rx_serdes_clk]
  connect_bd_net -net rx_serdes_reset_1  [get_bd_ports rx_serdes_reset] \
  [get_bd_pins mrmac_0/rx_serdes_reset]
  connect_bd_net -net rx_ts_clk_1  [get_bd_ports rx_ts_clk] \
  [get_bd_pins mrmac_0/rx_ts_clk]
  connect_bd_net -net s_axi_aclk_1  [get_bd_ports s_axi_aclk] \
  [get_bd_pins mrmac_0/s_axi_aclk]
  connect_bd_net -net s_axi_aresetn_1  [get_bd_ports s_axi_aresetn] \
  [get_bd_pins mrmac_0/s_axi_aresetn] \
  [get_bd_pins gt_quad_base/apb3presetn]
  connect_bd_net -net tx_alt_serdes_clk_1  [get_bd_ports tx_alt_serdes_clk] \
  [get_bd_pins mrmac_0/tx_alt_serdes_clk]
  connect_bd_net -net tx_axi_clk_1  [get_bd_ports tx_axi_clk] \
  [get_bd_pins mrmac_0/tx_axi_clk]
  connect_bd_net -net tx_axis_tdata0_1  [get_bd_ports tx_axis_tdata0] \
  [get_bd_pins mrmac_0/tx_axis_tdata0]
  connect_bd_net -net tx_axis_tdata1_1  [get_bd_ports tx_axis_tdata1] \
  [get_bd_pins mrmac_0/tx_axis_tdata1]
  connect_bd_net -net tx_axis_tdata2_1  [get_bd_ports tx_axis_tdata2] \
  [get_bd_pins mrmac_0/tx_axis_tdata2]
  connect_bd_net -net tx_axis_tdata3_1  [get_bd_ports tx_axis_tdata3] \
  [get_bd_pins mrmac_0/tx_axis_tdata3]
  connect_bd_net -net tx_axis_tdata4_1  [get_bd_ports tx_axis_tdata4] \
  [get_bd_pins mrmac_0/tx_axis_tdata4]
  connect_bd_net -net tx_axis_tdata5_1  [get_bd_ports tx_axis_tdata5] \
  [get_bd_pins mrmac_0/tx_axis_tdata5]
  connect_bd_net -net tx_axis_tdata6_1  [get_bd_ports tx_axis_tdata6] \
  [get_bd_pins mrmac_0/tx_axis_tdata6]
  connect_bd_net -net tx_axis_tdata7_1  [get_bd_ports tx_axis_tdata7] \
  [get_bd_pins mrmac_0/tx_axis_tdata7]
  connect_bd_net -net tx_axis_tkeep_user0_1  [get_bd_ports tx_axis_tkeep_user0] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user0]
  connect_bd_net -net tx_axis_tkeep_user1_1  [get_bd_ports tx_axis_tkeep_user1] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user1]
  connect_bd_net -net tx_axis_tkeep_user2_1  [get_bd_ports tx_axis_tkeep_user2] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user2]
  connect_bd_net -net tx_axis_tkeep_user3_1  [get_bd_ports tx_axis_tkeep_user3] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user3]
  connect_bd_net -net tx_axis_tkeep_user4_1  [get_bd_ports tx_axis_tkeep_user4] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user4]
  connect_bd_net -net tx_axis_tkeep_user5_1  [get_bd_ports tx_axis_tkeep_user5] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user5]
  connect_bd_net -net tx_axis_tkeep_user6_1  [get_bd_ports tx_axis_tkeep_user6] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user6]
  connect_bd_net -net tx_axis_tkeep_user7_1  [get_bd_ports tx_axis_tkeep_user7] \
  [get_bd_pins mrmac_0/tx_axis_tkeep_user7]
  connect_bd_net -net tx_axis_tlast_0_1  [get_bd_ports tx_axis_tlast_0] \
  [get_bd_pins mrmac_0/tx_axis_tlast_0]
  connect_bd_net -net tx_axis_tlast_1_1  [get_bd_ports tx_axis_tlast_1] \
  [get_bd_pins mrmac_0/tx_axis_tlast_1]
  connect_bd_net -net tx_axis_tlast_2_1  [get_bd_ports tx_axis_tlast_2] \
  [get_bd_pins mrmac_0/tx_axis_tlast_2]
  connect_bd_net -net tx_axis_tlast_3_1  [get_bd_ports tx_axis_tlast_3] \
  [get_bd_pins mrmac_0/tx_axis_tlast_3]
  connect_bd_net -net tx_axis_tvalid_0_1  [get_bd_ports tx_axis_tvalid_0] \
  [get_bd_pins mrmac_0/tx_axis_tvalid_0]
  connect_bd_net -net tx_axis_tvalid_1_1  [get_bd_ports tx_axis_tvalid_1] \
  [get_bd_pins mrmac_0/tx_axis_tvalid_1]
  connect_bd_net -net tx_axis_tvalid_2_1  [get_bd_ports tx_axis_tvalid_2] \
  [get_bd_pins mrmac_0/tx_axis_tvalid_2]
  connect_bd_net -net tx_axis_tvalid_3_1  [get_bd_ports tx_axis_tvalid_3] \
  [get_bd_pins mrmac_0/tx_axis_tvalid_3]
  connect_bd_net -net tx_core_clk_1  [get_bd_ports tx_core_clk] \
  [get_bd_pins mrmac_0/tx_core_clk]
  connect_bd_net -net tx_core_reset_1  [get_bd_ports tx_core_reset] \
  [get_bd_pins mrmac_0/tx_core_reset]
  connect_bd_net -net tx_flexif_clk_1  [get_bd_ports tx_flexif_clk] \
  [get_bd_pins mrmac_0/tx_flexif_clk]
  connect_bd_net -net tx_serdes_reset_1  [get_bd_ports tx_serdes_reset] \
  [get_bd_pins mrmac_0/tx_serdes_reset]
  connect_bd_net -net tx_ts_clk_1  [get_bd_ports tx_ts_clk] \
  [get_bd_pins mrmac_0/tx_ts_clk]
  connect_bd_net -net util_ds_buf_0_IBUF_OUT  [get_bd_pins util_ds_buf_0/IBUF_OUT] \
  [get_bd_pins gt_quad_base/GT_REFCLK0]
  connect_bd_net -net xlconst_mbufg_0_dout  [get_bd_pins xlconst_mbufg_0/dout] \
  [get_bd_pins mbufg_gt_0/MBUFG_GT_CE] \
  [get_bd_pins mbufg_gt_0_1/MBUFG_GT_CE] \
  [get_bd_pins mbufg_gt_1/MBUFG_GT_CE] \
  [get_bd_pins mbufg_gt_1_1/MBUFG_GT_CE]

  # Create address segments
  assign_bd_address -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces APB3_INTF] [get_bd_addr_segs gt_quad_base/APB3_INTF/Reg] -force
  assign_bd_address -offset 0x44A00000 -range 0x00010000 -target_address_space [get_bd_addr_spaces s_axi] [get_bd_addr_segs mrmac_0/s_axi/Reg] -force


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_MRMAC_block_automation()

cr_bd_MRMAC_block_automation ""
set_property REGISTERED_WITH_MANAGER "1" [get_files MRMAC_block_automation.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files MRMAC_block_automation.bd ] 

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcve2302-sfva784-1LP-e-S -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcve2302-sfva784-1LP-e-S" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcve2302-sfva784-1LP-e-S -flow {Vivado Advanced Implementation 2025} -strategy "Vivado Advanced Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Advanced Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Advanced Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Advanced Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcve2302-sfva784-1LP-e-S" -objects $obj
set_property -name "strategy" -value "Vivado Advanced Implementation Defaults" -objects $obj
set_property -name "steps.place_design.args.subdirective" -value "" -objects $obj
set_property -name "steps.write_device_image.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_device_image.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
